/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Price from './Price';

/**
 * The Addon model module.
 * @module model/Addon
 * @version v2
 */
class Addon {
    /**
     * Constructs a new <code>Addon</code>.
     * @alias module:model/Addon
     */
    constructor() { 
        
        Addon.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Addon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Addon} obj Optional instance to populate.
     * @return {module:model/Addon} The populated <code>Addon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Addon();

            if (data.hasOwnProperty('addon_id')) {
                obj['addon_id'] = ApiClient.convertToType(data['addon_id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('display_order')) {
                obj['display_order'] = ApiClient.convertToType(data['display_order'], 'Number');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('ListPrice')) {
                obj['ListPrice'] = Price.constructFromObject(data['ListPrice']);
            }
            if (data.hasOwnProperty('FinalPrice')) {
                obj['FinalPrice'] = Price.constructFromObject(data['FinalPrice']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Addon</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Addon</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // validate the optional field `ListPrice`
        if (data['ListPrice']) { // data not null
          Price.validateJSON(data['ListPrice']);
        }
        // validate the optional field `FinalPrice`
        if (data['FinalPrice']) { // data not null
          Price.validateJSON(data['FinalPrice']);
        }

        return true;
    }


}



/**
 * @member {Number} addon_id
 */
Addon.prototype['addon_id'] = undefined;

/**
 * @member {String} title
 */
Addon.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Addon.prototype['description'] = undefined;

/**
 * @member {String} type
 */
Addon.prototype['type'] = undefined;

/**
 * @member {module:model/Addon.StateEnum} state
 */
Addon.prototype['state'] = undefined;

/**
 * @member {Number} display_order
 */
Addon.prototype['display_order'] = undefined;

/**
 * @member {Boolean} default
 */
Addon.prototype['default'] = undefined;

/**
 * @member {module:model/Price} ListPrice
 */
Addon.prototype['ListPrice'] = undefined;

/**
 * @member {module:model/Price} FinalPrice
 */
Addon.prototype['FinalPrice'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
Addon['StateEnum'] = {

    /**
     * value: "visible"
     * @const
     */
    "visible": "visible",

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled"
};



export default Addon;

