/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnalyticGraphDataPoint model module.
 * @module model/AnalyticGraphDataPoint
 * @version v2
 */
class AnalyticGraphDataPoint {
    /**
     * Constructs a new <code>AnalyticGraphDataPoint</code>.
     * @alias module:model/AnalyticGraphDataPoint
     */
    constructor() { 
        
        AnalyticGraphDataPoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnalyticGraphDataPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnalyticGraphDataPoint} obj Optional instance to populate.
     * @return {module:model/AnalyticGraphDataPoint} The populated <code>AnalyticGraphDataPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalyticGraphDataPoint();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('ts')) {
                obj['ts'] = ApiClient.convertToType(data['ts'], 'Number');
            }
            if (data.hasOwnProperty('days')) {
                obj['days'] = ApiClient.convertToType(data['days'], 'Number');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], {'String': 'Number'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnalyticGraphDataPoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalyticGraphDataPoint</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }

        return true;
    }


}



/**
 * @member {String} label
 */
AnalyticGraphDataPoint.prototype['label'] = undefined;

/**
 * @member {Number} count
 */
AnalyticGraphDataPoint.prototype['count'] = undefined;

/**
 * @member {Number} ts
 */
AnalyticGraphDataPoint.prototype['ts'] = undefined;

/**
 * @member {Number} days
 */
AnalyticGraphDataPoint.prototype['days'] = undefined;

/**
 * @member {Object.<String, Number>} values
 */
AnalyticGraphDataPoint.prototype['values'] = undefined;






export default AnalyticGraphDataPoint;

