/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnalyticGraphDataPeriod from './AnalyticGraphDataPeriod';
import AnalyticGraphDataPoint from './AnalyticGraphDataPoint';

/**
 * The AnalyticGraphData model module.
 * @module model/AnalyticGraphData
 * @version v2
 */
class AnalyticGraphData {
    /**
     * Constructs a new <code>AnalyticGraphData</code>.
     * @alias module:model/AnalyticGraphData
     */
    constructor() { 
        
        AnalyticGraphData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnalyticGraphData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnalyticGraphData} obj Optional instance to populate.
     * @return {module:model/AnalyticGraphData} The populated <code>AnalyticGraphData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalyticGraphData();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], {'String': AnalyticGraphDataPoint});
            }
            if (data.hasOwnProperty('grouping')) {
                obj['grouping'] = ApiClient.convertToType(data['grouping'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = AnalyticGraphDataPeriod.constructFromObject(data['period']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnalyticGraphData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalyticGraphData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['grouping'] && !(typeof data['grouping'] === 'string' || data['grouping'] instanceof String)) {
            throw new Error("Expected the field `grouping` to be a primitive type in the JSON string but got " + data['grouping']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // validate the optional field `period`
        if (data['period']) { // data not null
          AnalyticGraphDataPeriod.validateJSON(data['period']);
        }

        return true;
    }


}



/**
 * @member {Object.<String, module:model/AnalyticGraphDataPoint>} data
 */
AnalyticGraphData.prototype['data'] = undefined;

/**
 * @member {String} grouping
 */
AnalyticGraphData.prototype['grouping'] = undefined;

/**
 * @member {String} label
 */
AnalyticGraphData.prototype['label'] = undefined;

/**
 * @member {module:model/AnalyticGraphDataPeriod} period
 */
AnalyticGraphData.prototype['period'] = undefined;






export default AnalyticGraphData;

