/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Analytic model module.
 * @module model/Analytic
 * @version v2
 */
class Analytic {
    /**
     * Constructs a new <code>Analytic</code>.
     * @alias module:model/Analytic
     */
    constructor() { 
        
        Analytic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Analytic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Analytic} obj Optional instance to populate.
     * @return {module:model/Analytic} The populated <code>Analytic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Analytic();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('graph')) {
                obj['graph'] = ApiClient.convertToType(data['graph'], 'Boolean');
            }
            if (data.hasOwnProperty('single')) {
                obj['single'] = ApiClient.convertToType(data['single'], 'Boolean');
            }
            if (data.hasOwnProperty('filters')) {
                obj['filters'] = ApiClient.convertToType(data['filters'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Analytic</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Analytic</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['desc'] && !(typeof data['desc'] === 'string' || data['desc'] instanceof String)) {
            throw new Error("Expected the field `desc` to be a primitive type in the JSON string but got " + data['desc']);
        }
        // ensure the json data is a string
        if (data['filters'] && !(typeof data['filters'] === 'string' || data['filters'] instanceof String)) {
            throw new Error("Expected the field `filters` to be a primitive type in the JSON string but got " + data['filters']);
        }

        return true;
    }


}



/**
 * @member {String} label
 */
Analytic.prototype['label'] = undefined;

/**
 * @member {String} desc
 */
Analytic.prototype['desc'] = undefined;

/**
 * Whether or not this analytic can be requested via the /v2/analytics/graph endpoint.
 * @member {Boolean} graph
 */
Analytic.prototype['graph'] = undefined;

/**
 * Whether or not this analytic can be requested via the /v2/analytics/single endpoint.
 * @member {Boolean} single
 */
Analytic.prototype['single'] = undefined;

/**
 * @member {String} filters
 */
Analytic.prototype['filters'] = undefined;






export default Analytic;

