/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartSummary model module.
 * @module model/CartSummary
 * @version v2
 */
class CartSummary {
    /**
     * Constructs a new <code>CartSummary</code>.
     * @alias module:model/CartSummary
     * @param listPrice {Number} The combined listed price of all items in the cart (ie. the original prices without any discounts applied).
     * @param listPriceFormatted {String} The list price formatted as a string using the given currency.  A list price of 5 would be formatted as `$5.00`.
     * @param finalPrice {Number} The combined final price of all items in the cart (ie. with discounts applied). This is the subtotal the user would pay upon checkout initiation, minus any applicable sales tax.
     * @param finalPriceFormatted {String} The final price formatted as a string using the given currency.  A final price of 5 would be formatted as `$5.00`.
     * @param currency {String} The currency code (ISO 4217) of the prices in this summary.  Will be USD for all transactions through BuiltByBit.
     */
    constructor(listPrice, listPriceFormatted, finalPrice, finalPriceFormatted, currency) { 
        
        CartSummary.initialize(this, listPrice, listPriceFormatted, finalPrice, finalPriceFormatted, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, listPrice, listPriceFormatted, finalPrice, finalPriceFormatted, currency) { 
        obj['list_price'] = listPrice;
        obj['list_price_formatted'] = listPriceFormatted;
        obj['final_price'] = finalPrice;
        obj['final_price_formatted'] = finalPriceFormatted;
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>CartSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartSummary} obj Optional instance to populate.
     * @return {module:model/CartSummary} The populated <code>CartSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartSummary();

            if (data.hasOwnProperty('list_price')) {
                obj['list_price'] = ApiClient.convertToType(data['list_price'], 'Number');
            }
            if (data.hasOwnProperty('list_price_formatted')) {
                obj['list_price_formatted'] = ApiClient.convertToType(data['list_price_formatted'], 'String');
            }
            if (data.hasOwnProperty('final_price')) {
                obj['final_price'] = ApiClient.convertToType(data['final_price'], 'Number');
            }
            if (data.hasOwnProperty('final_price_formatted')) {
                obj['final_price_formatted'] = ApiClient.convertToType(data['final_price_formatted'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('notice')) {
                obj['notice'] = ApiClient.convertToType(data['notice'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CartSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CartSummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CartSummary.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['list_price_formatted'] && !(typeof data['list_price_formatted'] === 'string' || data['list_price_formatted'] instanceof String)) {
            throw new Error("Expected the field `list_price_formatted` to be a primitive type in the JSON string but got " + data['list_price_formatted']);
        }
        // ensure the json data is a string
        if (data['final_price_formatted'] && !(typeof data['final_price_formatted'] === 'string' || data['final_price_formatted'] instanceof String)) {
            throw new Error("Expected the field `final_price_formatted` to be a primitive type in the JSON string but got " + data['final_price_formatted']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['notice'] && !(typeof data['notice'] === 'string' || data['notice'] instanceof String)) {
            throw new Error("Expected the field `notice` to be a primitive type in the JSON string but got " + data['notice']);
        }

        return true;
    }


}

CartSummary.RequiredProperties = ["list_price", "list_price_formatted", "final_price", "final_price_formatted", "currency"];

/**
 * The combined listed price of all items in the cart (ie. the original prices without any discounts applied).
 * @member {Number} list_price
 */
CartSummary.prototype['list_price'] = undefined;

/**
 * The list price formatted as a string using the given currency.  A list price of 5 would be formatted as `$5.00`.
 * @member {String} list_price_formatted
 */
CartSummary.prototype['list_price_formatted'] = undefined;

/**
 * The combined final price of all items in the cart (ie. with discounts applied). This is the subtotal the user would pay upon checkout initiation, minus any applicable sales tax.
 * @member {Number} final_price
 */
CartSummary.prototype['final_price'] = undefined;

/**
 * The final price formatted as a string using the given currency.  A final price of 5 would be formatted as `$5.00`.
 * @member {String} final_price_formatted
 */
CartSummary.prototype['final_price_formatted'] = undefined;

/**
 * The currency code (ISO 4217) of the prices in this summary.  Will be USD for all transactions through BuiltByBit.
 * @member {String} currency
 */
CartSummary.prototype['currency'] = undefined;

/**
 * A message to display to the user as a notice regarding their current cart items. We may use this to inform the user that they have a previous pending checkout which is yet to be fulfilled (either because the payment is still pending or because they closed out of the checkout).
 * @member {String} notice
 */
CartSummary.prototype['notice'] = undefined;






export default CartSummary;

