/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Price from './Price';

/**
 * The CartItem model module.
 * @module model/CartItem
 * @version v2
 */
class CartItem {
    /**
     * Constructs a new <code>CartItem</code>.
     * @alias module:model/CartItem
     */
    constructor() { 
        
        CartItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CartItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartItem} obj Optional instance to populate.
     * @return {module:model/CartItem} The populated <code>CartItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartItem();

            if (data.hasOwnProperty('cart_item_id')) {
                obj['cart_item_id'] = ApiClient.convertToType(data['cart_item_id'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('content_id')) {
                obj['content_id'] = ApiClient.convertToType(data['content_id'], 'Number');
            }
            if (data.hasOwnProperty('content_title')) {
                obj['content_title'] = ApiClient.convertToType(data['content_title'], 'String');
            }
            if (data.hasOwnProperty('content_summary')) {
                obj['content_summary'] = ApiClient.convertToType(data['content_summary'], 'String');
            }
            if (data.hasOwnProperty('content_cover_image_url')) {
                obj['content_cover_image_url'] = ApiClient.convertToType(data['content_cover_image_url'], 'String');
            }
            if (data.hasOwnProperty('ListPrice')) {
                obj['ListPrice'] = Price.constructFromObject(data['ListPrice']);
            }
            if (data.hasOwnProperty('FinalPrice')) {
                obj['FinalPrice'] = Price.constructFromObject(data['FinalPrice']);
            }
            if (data.hasOwnProperty('discounts')) {
                obj['discounts'] = ApiClient.convertToType(data['discounts'], {'String': Price});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CartItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CartItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cart_item_id'] && !(typeof data['cart_item_id'] === 'string' || data['cart_item_id'] instanceof String)) {
            throw new Error("Expected the field `cart_item_id` to be a primitive type in the JSON string but got " + data['cart_item_id']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is a string
        if (data['content_title'] && !(typeof data['content_title'] === 'string' || data['content_title'] instanceof String)) {
            throw new Error("Expected the field `content_title` to be a primitive type in the JSON string but got " + data['content_title']);
        }
        // ensure the json data is a string
        if (data['content_summary'] && !(typeof data['content_summary'] === 'string' || data['content_summary'] instanceof String)) {
            throw new Error("Expected the field `content_summary` to be a primitive type in the JSON string but got " + data['content_summary']);
        }
        // ensure the json data is a string
        if (data['content_cover_image_url'] && !(typeof data['content_cover_image_url'] === 'string' || data['content_cover_image_url'] instanceof String)) {
            throw new Error("Expected the field `content_cover_image_url` to be a primitive type in the JSON string but got " + data['content_cover_image_url']);
        }
        // validate the optional field `ListPrice`
        if (data['ListPrice']) { // data not null
          Price.validateJSON(data['ListPrice']);
        }
        // validate the optional field `FinalPrice`
        if (data['FinalPrice']) { // data not null
          Price.validateJSON(data['FinalPrice']);
        }

        return true;
    }


}



/**
 * @member {String} cart_item_id
 */
CartItem.prototype['cart_item_id'] = undefined;

/**
 * @member {String} content_type
 */
CartItem.prototype['content_type'] = undefined;

/**
 * @member {Number} content_id
 */
CartItem.prototype['content_id'] = undefined;

/**
 * @member {String} content_title
 */
CartItem.prototype['content_title'] = undefined;

/**
 * @member {String} content_summary
 */
CartItem.prototype['content_summary'] = undefined;

/**
 * @member {String} content_cover_image_url
 */
CartItem.prototype['content_cover_image_url'] = undefined;

/**
 * @member {module:model/Price} ListPrice
 */
CartItem.prototype['ListPrice'] = undefined;

/**
 * @member {module:model/Price} FinalPrice
 */
CartItem.prototype['FinalPrice'] = undefined;

/**
 * @member {Object.<String, module:model/Price>} discounts
 */
CartItem.prototype['discounts'] = undefined;






export default CartItem;

