/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Category model module.
 * @module model/Category
 * @version v2
 */
class Category {
    /**
     * Constructs a new <code>Category</code>.
     * @alias module:model/Category
     * @param categoryId {Number} 
     * @param categoryUrl {String} 
     * @param title {String} 
     */
    constructor(categoryId, categoryUrl, title) { 
        
        Category.initialize(this, categoryId, categoryUrl, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categoryId, categoryUrl, title) { 
        obj['category_id'] = categoryId;
        obj['category_url'] = categoryUrl;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Category} obj Optional instance to populate.
     * @return {module:model/Category} The populated <code>Category</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Category();

            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Number');
            }
            if (data.hasOwnProperty('category_url')) {
                obj['category_url'] = ApiClient.convertToType(data['category_url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('fa_icon')) {
                obj['fa_icon'] = ApiClient.convertToType(data['fa_icon'], 'String');
            }
            if (data.hasOwnProperty('platform_image_url')) {
                obj['platform_image_url'] = ApiClient.convertToType(data['platform_image_url'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('Children')) {
                obj['Children'] = ApiClient.convertToType(data['Children'], [Category]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Category</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Category</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Category.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['category_url'] && !(typeof data['category_url'] === 'string' || data['category_url'] instanceof String)) {
            throw new Error("Expected the field `category_url` to be a primitive type in the JSON string but got " + data['category_url']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['fa_icon'] && !(typeof data['fa_icon'] === 'string' || data['fa_icon'] instanceof String)) {
            throw new Error("Expected the field `fa_icon` to be a primitive type in the JSON string but got " + data['fa_icon']);
        }
        // ensure the json data is a string
        if (data['platform_image_url'] && !(typeof data['platform_image_url'] === 'string' || data['platform_image_url'] instanceof String)) {
            throw new Error("Expected the field `platform_image_url` to be a primitive type in the JSON string but got " + data['platform_image_url']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        if (data['Children']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Children'])) {
                throw new Error("Expected the field `Children` to be an array in the JSON data but got " + data['Children']);
            }
            // validate the optional field `Children` (array)
            for (const item of data['Children']) {
                Category.validateJSON(item);
            };
        }

        return true;
    }


}

Category.RequiredProperties = ["category_id", "category_url", "title"];

/**
 * @member {Number} category_id
 */
Category.prototype['category_id'] = undefined;

/**
 * @member {String} category_url
 */
Category.prototype['category_url'] = undefined;

/**
 * @member {String} description
 */
Category.prototype['description'] = undefined;

/**
 * @member {String} fa_icon
 */
Category.prototype['fa_icon'] = undefined;

/**
 * @member {String} platform_image_url
 */
Category.prototype['platform_image_url'] = undefined;

/**
 * @member {String} title
 */
Category.prototype['title'] = undefined;

/**
 * @member {Array.<module:model/Category>} Children
 */
Category.prototype['Children'] = undefined;






export default Category;

