/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Coupon model module.
 * @module model/Coupon
 * @version v2
 */
class Coupon {
    /**
     * Constructs a new <code>Coupon</code>.
     * @alias module:model/Coupon
     */
    constructor() { 
        
        Coupon.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Coupon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Coupon} obj Optional instance to populate.
     * @return {module:model/Coupon} The populated <code>Coupon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Coupon();

            if (data.hasOwnProperty('coupon_id')) {
                obj['coupon_id'] = ApiClient.convertToType(data['coupon_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Boolean');
            }
            if (data.hasOwnProperty('all_content_types')) {
                obj['all_content_types'] = ApiClient.convertToType(data['all_content_types'], ['String']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'Number');
            }
            if (data.hasOwnProperty('max_uses')) {
                obj['max_uses'] = ApiClient.convertToType(data['max_uses'], 'Number');
            }
            if (data.hasOwnProperty('max_per_user_uses')) {
                obj['max_per_user_uses'] = ApiClient.convertToType(data['max_per_user_uses'], 'Number');
            }
            if (data.hasOwnProperty('uses')) {
                obj['uses'] = ApiClient.convertToType(data['uses'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Coupon</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Coupon</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['all_content_types'])) {
            throw new Error("Expected the field `all_content_types` to be an array in the JSON data but got " + data['all_content_types']);
        }

        return true;
    }


}



/**
 * @member {Number} coupon_id
 */
Coupon.prototype['coupon_id'] = undefined;

/**
 * @member {Number} user_id
 */
Coupon.prototype['user_id'] = undefined;

/**
 * This is the code a buyer would enter at checkout.
 * @member {String} label
 */
Coupon.prototype['label'] = undefined;

/**
 * The discount to apply. Either a fixed value, or a decimal percent. Depends on the 'percent' field.
 * @member {Number} discount
 */
Coupon.prototype['discount'] = undefined;

/**
 * If true, the 'discount' field represents a decimal percentage.  If false, the 'discount' field represents an absolute $ USD value.
 * @member {Boolean} percent
 */
Coupon.prototype['percent'] = undefined;

/**
 *  A list of content types for which this coupon code applies to without requiring an entry. Eg. if you created the coupon with the 'All resources' option selected, this list will include \"resource\".
 * @member {Array.<String>} all_content_types
 */
Coupon.prototype['all_content_types'] = undefined;

/**
 * A UNIX timestamp.
 * @member {Number} created_at
 */
Coupon.prototype['created_at'] = undefined;

/**
 * A UNIX timestamp.
 * @member {Number} expires_at
 */
Coupon.prototype['expires_at'] = undefined;

/**
 * @member {Number} max_uses
 */
Coupon.prototype['max_uses'] = undefined;

/**
 * @member {Number} max_per_user_uses
 */
Coupon.prototype['max_per_user_uses'] = undefined;

/**
 * @member {Number} uses
 */
Coupon.prototype['uses'] = undefined;

/**
 * Whether or not the coupon code is active and can still be used at checkout. Accounts for the expiry date if set and the max use limit if set.
 * @member {Boolean} active
 */
Coupon.prototype['active'] = undefined;






export default Coupon;

