/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Addon from './Addon';
import Bundle from './Bundle';
import Coupon from './Coupon';
import Resource from './Resource';

/**
 * The CouponEntry model module.
 * @module model/CouponEntry
 * @version v2
 */
class CouponEntry {
    /**
     * Constructs a new <code>CouponEntry</code>.
     * @alias module:model/CouponEntry
     */
    constructor() { 
        
        CouponEntry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CouponEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CouponEntry} obj Optional instance to populate.
     * @return {module:model/CouponEntry} The populated <code>CouponEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CouponEntry();

            if (data.hasOwnProperty('entry_id')) {
                obj['entry_id'] = ApiClient.convertToType(data['entry_id'], 'Number');
            }
            if (data.hasOwnProperty('coupon_id')) {
                obj['coupon_id'] = ApiClient.convertToType(data['coupon_id'], 'Number');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('content_id')) {
                obj['content_id'] = ApiClient.convertToType(data['content_id'], 'Number');
            }
            if (data.hasOwnProperty('Coupon')) {
                obj['Coupon'] = Coupon.constructFromObject(data['Coupon']);
            }
            if (data.hasOwnProperty('Resource')) {
                obj['Resource'] = Resource.constructFromObject(data['Resource']);
            }
            if (data.hasOwnProperty('Addon')) {
                obj['Addon'] = Addon.constructFromObject(data['Addon']);
            }
            if (data.hasOwnProperty('Bundle')) {
                obj['Bundle'] = Bundle.constructFromObject(data['Bundle']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CouponEntry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CouponEntry</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // validate the optional field `Coupon`
        if (data['Coupon']) { // data not null
          Coupon.validateJSON(data['Coupon']);
        }
        // validate the optional field `Resource`
        if (data['Resource']) { // data not null
          Resource.validateJSON(data['Resource']);
        }
        // validate the optional field `Addon`
        if (data['Addon']) { // data not null
          Addon.validateJSON(data['Addon']);
        }
        // validate the optional field `Bundle`
        if (data['Bundle']) { // data not null
          Bundle.validateJSON(data['Bundle']);
        }

        return true;
    }


}



/**
 * @member {Number} entry_id
 */
CouponEntry.prototype['entry_id'] = undefined;

/**
 * @member {Number} coupon_id
 */
CouponEntry.prototype['coupon_id'] = undefined;

/**
 * @member {String} content_type
 */
CouponEntry.prototype['content_type'] = undefined;

/**
 * @member {Number} content_id
 */
CouponEntry.prototype['content_id'] = undefined;

/**
 * @member {module:model/Coupon} Coupon
 */
CouponEntry.prototype['Coupon'] = undefined;

/**
 * @member {module:model/Resource} Resource
 */
CouponEntry.prototype['Resource'] = undefined;

/**
 * @member {module:model/Addon} Addon
 */
CouponEntry.prototype['Addon'] = undefined;

/**
 * @member {module:model/Bundle} Bundle
 */
CouponEntry.prototype['Bundle'] = undefined;






export default CouponEntry;

