/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Description model module.
 * @module model/Description
 * @version v2
 */
class Description {
    /**
     * Constructs a new <code>Description</code>.
     * @alias module:model/Description
     */
    constructor() { 
        
        Description.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Description</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Description} obj Optional instance to populate.
     * @return {module:model/Description} The populated <code>Description</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Description();

            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('bbcode')) {
                obj['bbcode'] = ApiClient.convertToType(data['bbcode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Description</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Description</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['html'] && !(typeof data['html'] === 'string' || data['html'] instanceof String)) {
            throw new Error("Expected the field `html` to be a primitive type in the JSON string but got " + data['html']);
        }
        // ensure the json data is a string
        if (data['bbcode'] && !(typeof data['bbcode'] === 'string' || data['bbcode'] instanceof String)) {
            throw new Error("Expected the field `bbcode` to be a primitive type in the JSON string but got " + data['bbcode']);
        }

        return true;
    }


}



/**
 * @member {String} html
 */
Description.prototype['html'] = undefined;

/**
 * @member {String} bbcode
 */
Description.prototype['bbcode'] = undefined;






export default Description;

