/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FilterChoice from './FilterChoice';

/**
 * The Filter model module.
 * @module model/Filter
 * @version v2
 */
class Filter {
    /**
     * Constructs a new <code>Filter</code>.
     * @alias module:model/Filter
     * @param filterId {String} 
     * @param order {Number} The display order of this filter. Filters on BuiltByBit are displayed in ascending order of their order value. 
     * @param primary {Boolean} Whether or not BuiltByBit considers this a primary filter. Primary filters are displayed more prominently.
     * @param title {String} 
     * @param type {String} Supported types:    'choice': a finite choice set (see `options`).    'text': user text input
     */
    constructor(filterId, order, primary, title, type) { 
        
        Filter.initialize(this, filterId, order, primary, title, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, filterId, order, primary, title, type) { 
        obj['filter_id'] = filterId;
        obj['order'] = order;
        obj['primary'] = primary;
        obj['title'] = title;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Filter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Filter} obj Optional instance to populate.
     * @return {module:model/Filter} The populated <code>Filter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Filter();

            if (data.hasOwnProperty('filter_id')) {
                obj['filter_id'] = ApiClient.convertToType(data['filter_id'], 'String');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('primary')) {
                obj['primary'] = ApiClient.convertToType(data['primary'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], [FilterChoice]);
            }
            if (data.hasOwnProperty('query_field')) {
                obj['query_field'] = ApiClient.convertToType(data['query_field'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Filter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Filter</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Filter.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['filter_id'] && !(typeof data['filter_id'] === 'string' || data['filter_id'] instanceof String)) {
            throw new Error("Expected the field `filter_id` to be a primitive type in the JSON string but got " + data['filter_id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        if (data['choices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['choices'])) {
                throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
            }
            // validate the optional field `choices` (array)
            for (const item of data['choices']) {
                FilterChoice.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['query_field'] && !(typeof data['query_field'] === 'string' || data['query_field'] instanceof String)) {
            throw new Error("Expected the field `query_field` to be a primitive type in the JSON string but got " + data['query_field']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

Filter.RequiredProperties = ["filter_id", "order", "primary", "title", "type"];

/**
 * @member {String} filter_id
 */
Filter.prototype['filter_id'] = undefined;

/**
 * The display order of this filter. Filters on BuiltByBit are displayed in ascending order of their order value. 
 * @member {Number} order
 */
Filter.prototype['order'] = undefined;

/**
 * Whether or not BuiltByBit considers this a primary filter. Primary filters are displayed more prominently.
 * @member {Boolean} primary
 */
Filter.prototype['primary'] = undefined;

/**
 * @member {String} title
 */
Filter.prototype['title'] = undefined;

/**
 * Supported types:    'choice': a finite choice set (see `options`).    'text': user text input
 * @member {String} type
 */
Filter.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/FilterChoice>} choices
 */
Filter.prototype['choices'] = undefined;

/**
 * @member {String} query_field
 */
Filter.prototype['query_field'] = undefined;

/**
 * The pass-through value of this filter, only applicable where type = `text`.
 * @member {String} value
 */
Filter.prototype['value'] = undefined;






export default Filter;

