/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetOauth2TokenRevoke200Response model module.
 * @module model/GetOauth2TokenRevoke200Response
 * @version v2
 */
class GetOauth2TokenRevoke200Response {
    /**
     * Constructs a new <code>GetOauth2TokenRevoke200Response</code>.
     * @alias module:model/GetOauth2TokenRevoke200Response
     * @param revoked {Boolean} 
     */
    constructor(revoked) { 
        
        GetOauth2TokenRevoke200Response.initialize(this, revoked);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, revoked) { 
        obj['revoked'] = revoked || true;
    }

    /**
     * Constructs a <code>GetOauth2TokenRevoke200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetOauth2TokenRevoke200Response} obj Optional instance to populate.
     * @return {module:model/GetOauth2TokenRevoke200Response} The populated <code>GetOauth2TokenRevoke200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetOauth2TokenRevoke200Response();

            if (data.hasOwnProperty('revoked')) {
                obj['revoked'] = ApiClient.convertToType(data['revoked'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetOauth2TokenRevoke200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetOauth2TokenRevoke200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetOauth2TokenRevoke200Response.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GetOauth2TokenRevoke200Response.RequiredProperties = ["revoked"];

/**
 * @member {Boolean} revoked
 * @default true
 */
GetOauth2TokenRevoke200Response.prototype['revoked'] = true;






export default GetOauth2TokenRevoke200Response;

