/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Filter from './Filter';
import ListStats from './ListStats';
import Resource from './Resource';

/**
 * The GetResourcesDiscoverResources200ResponseData model module.
 * @module model/GetResourcesDiscoverResources200ResponseData
 * @version v2
 */
class GetResourcesDiscoverResources200ResponseData {
    /**
     * Constructs a new <code>GetResourcesDiscoverResources200ResponseData</code>.
     * @alias module:model/GetResourcesDiscoverResources200ResponseData
     * @param resources {Array.<module:model/Resource>} 
     * @param stats {module:model/ListStats} 
     */
    constructor(resources, stats) { 
        
        GetResourcesDiscoverResources200ResponseData.initialize(this, resources, stats);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resources, stats) { 
        obj['resources'] = resources;
        obj['stats'] = stats;
    }

    /**
     * Constructs a <code>GetResourcesDiscoverResources200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetResourcesDiscoverResources200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetResourcesDiscoverResources200ResponseData} The populated <code>GetResourcesDiscoverResources200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetResourcesDiscoverResources200ResponseData();

            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], [Resource]);
            }
            if (data.hasOwnProperty('filters')) {
                obj['filters'] = ApiClient.convertToType(data['filters'], [Filter]);
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ListStats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetResourcesDiscoverResources200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetResourcesDiscoverResources200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetResourcesDiscoverResources200ResponseData.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['resources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['resources'])) {
                throw new Error("Expected the field `resources` to be an array in the JSON data but got " + data['resources']);
            }
            // validate the optional field `resources` (array)
            for (const item of data['resources']) {
                Resource.validateJSON(item);
            };
        }
        if (data['filters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['filters'])) {
                throw new Error("Expected the field `filters` to be an array in the JSON data but got " + data['filters']);
            }
            // validate the optional field `filters` (array)
            for (const item of data['filters']) {
                Filter.validateJSON(item);
            };
        }
        // validate the optional field `stats`
        if (data['stats']) { // data not null
          ListStats.validateJSON(data['stats']);
        }

        return true;
    }


}

GetResourcesDiscoverResources200ResponseData.RequiredProperties = ["resources", "stats"];

/**
 * @member {Array.<module:model/Resource>} resources
 */
GetResourcesDiscoverResources200ResponseData.prototype['resources'] = undefined;

/**
 * @member {Array.<module:model/Filter>} filters
 */
GetResourcesDiscoverResources200ResponseData.prototype['filters'] = undefined;

/**
 * @member {module:model/ListStats} stats
 */
GetResourcesDiscoverResources200ResponseData.prototype['stats'] = undefined;






export default GetResourcesDiscoverResources200ResponseData;

