/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetResourcesDiscoverResources200ResponseData from './GetResourcesDiscoverResources200ResponseData';

/**
 * The GetResourcesDiscoverResources200Response model module.
 * @module model/GetResourcesDiscoverResources200Response
 * @version v2
 */
class GetResourcesDiscoverResources200Response {
    /**
     * Constructs a new <code>GetResourcesDiscoverResources200Response</code>.
     * @alias module:model/GetResourcesDiscoverResources200Response
     */
    constructor() { 
        
        GetResourcesDiscoverResources200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetResourcesDiscoverResources200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetResourcesDiscoverResources200Response} obj Optional instance to populate.
     * @return {module:model/GetResourcesDiscoverResources200Response} The populated <code>GetResourcesDiscoverResources200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetResourcesDiscoverResources200Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetResourcesDiscoverResources200ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetResourcesDiscoverResources200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetResourcesDiscoverResources200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          GetResourcesDiscoverResources200ResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {String} result
 * @default 'sucess'
 */
GetResourcesDiscoverResources200Response.prototype['result'] = 'sucess';

/**
 * @member {module:model/GetResourcesDiscoverResources200ResponseData} data
 */
GetResourcesDiscoverResources200Response.prototype['data'] = undefined;






export default GetResourcesDiscoverResources200Response;

