/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';

/**
 * The GetResourcesDiscoverCategories200ResponseData model module.
 * @module model/GetResourcesDiscoverCategories200ResponseData
 * @version v2
 */
class GetResourcesDiscoverCategories200ResponseData {
    /**
     * Constructs a new <code>GetResourcesDiscoverCategories200ResponseData</code>.
     * @alias module:model/GetResourcesDiscoverCategories200ResponseData
     */
    constructor() { 
        
        GetResourcesDiscoverCategories200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetResourcesDiscoverCategories200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetResourcesDiscoverCategories200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetResourcesDiscoverCategories200ResponseData} The populated <code>GetResourcesDiscoverCategories200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetResourcesDiscoverCategories200ResponseData();

            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [Category]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetResourcesDiscoverCategories200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetResourcesDiscoverCategories200ResponseData</code>.
     */
    static validateJSON(data) {
        if (data['categories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['categories'])) {
                throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
            }
            // validate the optional field `categories` (array)
            for (const item of data['categories']) {
                Category.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Category>} categories
 */
GetResourcesDiscoverCategories200ResponseData.prototype['categories'] = undefined;






export default GetResourcesDiscoverCategories200ResponseData;

