/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListStats from './ListStats';
import Purchase from './Purchase';

/**
 * The GetV2ResourcesCreatorPurchases200ResponseData model module.
 * @module model/GetV2ResourcesCreatorPurchases200ResponseData
 * @version v2
 */
class GetV2ResourcesCreatorPurchases200ResponseData {
    /**
     * Constructs a new <code>GetV2ResourcesCreatorPurchases200ResponseData</code>.
     * @alias module:model/GetV2ResourcesCreatorPurchases200ResponseData
     */
    constructor() { 
        
        GetV2ResourcesCreatorPurchases200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV2ResourcesCreatorPurchases200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV2ResourcesCreatorPurchases200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetV2ResourcesCreatorPurchases200ResponseData} The populated <code>GetV2ResourcesCreatorPurchases200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV2ResourcesCreatorPurchases200ResponseData();

            if (data.hasOwnProperty('purchases')) {
                obj['purchases'] = ApiClient.convertToType(data['purchases'], [Purchase]);
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ListStats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV2ResourcesCreatorPurchases200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV2ResourcesCreatorPurchases200ResponseData</code>.
     */
    static validateJSON(data) {
        if (data['purchases']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['purchases'])) {
                throw new Error("Expected the field `purchases` to be an array in the JSON data but got " + data['purchases']);
            }
            // validate the optional field `purchases` (array)
            for (const item of data['purchases']) {
                Purchase.validateJSON(item);
            };
        }
        // validate the optional field `stats`
        if (data['stats']) { // data not null
          ListStats.validateJSON(data['stats']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Purchase>} purchases
 */
GetV2ResourcesCreatorPurchases200ResponseData.prototype['purchases'] = undefined;

/**
 * @member {module:model/ListStats} stats
 */
GetV2ResourcesCreatorPurchases200ResponseData.prototype['stats'] = undefined;






export default GetV2ResourcesCreatorPurchases200ResponseData;

