/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coupon from './Coupon';
import ListStats from './ListStats';

/**
 * The GetV2ResourcesCreatorCoupons200ResponseData model module.
 * @module model/GetV2ResourcesCreatorCoupons200ResponseData
 * @version v2
 */
class GetV2ResourcesCreatorCoupons200ResponseData {
    /**
     * Constructs a new <code>GetV2ResourcesCreatorCoupons200ResponseData</code>.
     * @alias module:model/GetV2ResourcesCreatorCoupons200ResponseData
     */
    constructor() { 
        
        GetV2ResourcesCreatorCoupons200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV2ResourcesCreatorCoupons200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV2ResourcesCreatorCoupons200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetV2ResourcesCreatorCoupons200ResponseData} The populated <code>GetV2ResourcesCreatorCoupons200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV2ResourcesCreatorCoupons200ResponseData();

            if (data.hasOwnProperty('coupons')) {
                obj['coupons'] = ApiClient.convertToType(data['coupons'], [Coupon]);
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ListStats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV2ResourcesCreatorCoupons200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV2ResourcesCreatorCoupons200ResponseData</code>.
     */
    static validateJSON(data) {
        if (data['coupons']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['coupons'])) {
                throw new Error("Expected the field `coupons` to be an array in the JSON data but got " + data['coupons']);
            }
            // validate the optional field `coupons` (array)
            for (const item of data['coupons']) {
                Coupon.validateJSON(item);
            };
        }
        // validate the optional field `stats`
        if (data['stats']) { // data not null
          ListStats.validateJSON(data['stats']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Coupon>} coupons
 */
GetV2ResourcesCreatorCoupons200ResponseData.prototype['coupons'] = undefined;

/**
 * @member {module:model/ListStats} stats
 */
GetV2ResourcesCreatorCoupons200ResponseData.prototype['stats'] = undefined;






export default GetV2ResourcesCreatorCoupons200ResponseData;

