/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetV2AnalyticsSingle200ResponseDataPeriod model module.
 * @module model/GetV2AnalyticsSingle200ResponseDataPeriod
 * @version v2
 */
class GetV2AnalyticsSingle200ResponseDataPeriod {
    /**
     * Constructs a new <code>GetV2AnalyticsSingle200ResponseDataPeriod</code>.
     * @alias module:model/GetV2AnalyticsSingle200ResponseDataPeriod
     */
    constructor() { 
        
        GetV2AnalyticsSingle200ResponseDataPeriod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV2AnalyticsSingle200ResponseDataPeriod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV2AnalyticsSingle200ResponseDataPeriod} obj Optional instance to populate.
     * @return {module:model/GetV2AnalyticsSingle200ResponseDataPeriod} The populated <code>GetV2AnalyticsSingle200ResponseDataPeriod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV2AnalyticsSingle200ResponseDataPeriod();

            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'String');
            }
            if (data.hasOwnProperty('period_display')) {
                obj['period_display'] = ApiClient.convertToType(data['period_display'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'String');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV2AnalyticsSingle200ResponseDataPeriod</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV2AnalyticsSingle200ResponseDataPeriod</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['period'] && !(typeof data['period'] === 'string' || data['period'] instanceof String)) {
            throw new Error("Expected the field `period` to be a primitive type in the JSON string but got " + data['period']);
        }
        // ensure the json data is a string
        if (data['period_display'] && !(typeof data['period_display'] === 'string' || data['period_display'] instanceof String)) {
            throw new Error("Expected the field `period_display` to be a primitive type in the JSON string but got " + data['period_display']);
        }
        // ensure the json data is a string
        if (data['start_date'] && !(typeof data['start_date'] === 'string' || data['start_date'] instanceof String)) {
            throw new Error("Expected the field `start_date` to be a primitive type in the JSON string but got " + data['start_date']);
        }
        // ensure the json data is a string
        if (data['end_date'] && !(typeof data['end_date'] === 'string' || data['end_date'] instanceof String)) {
            throw new Error("Expected the field `end_date` to be a primitive type in the JSON string but got " + data['end_date']);
        }

        return true;
    }


}



/**
 * @member {String} period
 */
GetV2AnalyticsSingle200ResponseDataPeriod.prototype['period'] = undefined;

/**
 * @member {String} period_display
 */
GetV2AnalyticsSingle200ResponseDataPeriod.prototype['period_display'] = undefined;

/**
 * @member {String} start_date
 */
GetV2AnalyticsSingle200ResponseDataPeriod.prototype['start_date'] = undefined;

/**
 * @member {String} end_date
 */
GetV2AnalyticsSingle200ResponseDataPeriod.prototype['end_date'] = undefined;






export default GetV2AnalyticsSingle200ResponseDataPeriod;

