/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DownloadRequest from './DownloadRequest';

/**
 * The GetV2ResourcesEmbedDownloadInitiate200ResponseData model module.
 * @module model/GetV2ResourcesEmbedDownloadInitiate200ResponseData
 * @version v2
 */
class GetV2ResourcesEmbedDownloadInitiate200ResponseData {
    /**
     * Constructs a new <code>GetV2ResourcesEmbedDownloadInitiate200ResponseData</code>.
     * @alias module:model/GetV2ResourcesEmbedDownloadInitiate200ResponseData
     */
    constructor() { 
        
        GetV2ResourcesEmbedDownloadInitiate200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV2ResourcesEmbedDownloadInitiate200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV2ResourcesEmbedDownloadInitiate200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetV2ResourcesEmbedDownloadInitiate200ResponseData} The populated <code>GetV2ResourcesEmbedDownloadInitiate200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV2ResourcesEmbedDownloadInitiate200ResponseData();

            if (data.hasOwnProperty('request')) {
                obj['request'] = DownloadRequest.constructFromObject(data['request']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV2ResourcesEmbedDownloadInitiate200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV2ResourcesEmbedDownloadInitiate200ResponseData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `request`
        if (data['request']) { // data not null
          DownloadRequest.validateJSON(data['request']);
        }

        return true;
    }


}



/**
 * @member {module:model/DownloadRequest} request
 */
GetV2ResourcesEmbedDownloadInitiate200ResponseData.prototype['request'] = undefined;






export default GetV2ResourcesEmbedDownloadInitiate200ResponseData;

