/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Member model module.
 * @module model/Member
 * @version v2
 */
class Member {
    /**
     * Constructs a new <code>Member</code>.
     * @alias module:model/Member
     */
    constructor() { 
        
        Member.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Member</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Member} obj Optional instance to populate.
     * @return {module:model/Member} The populated <code>Member</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Member();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('user_url')) {
                obj['user_url'] = ApiClient.convertToType(data['user_url'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('registered_at')) {
                obj['registered_at'] = ApiClient.convertToType(data['registered_at'], 'String');
            }
            if (data.hasOwnProperty('avatar_url_large')) {
                obj['avatar_url_large'] = ApiClient.convertToType(data['avatar_url_large'], 'String');
            }
            if (data.hasOwnProperty('avatar_url_medium')) {
                obj['avatar_url_medium'] = ApiClient.convertToType(data['avatar_url_medium'], 'String');
            }
            if (data.hasOwnProperty('avatar_url_small')) {
                obj['avatar_url_small'] = ApiClient.convertToType(data['avatar_url_small'], 'String');
            }
            if (data.hasOwnProperty('banned')) {
                obj['banned'] = ApiClient.convertToType(data['banned'], 'Boolean');
            }
            if (data.hasOwnProperty('discord_id')) {
                obj['discord_id'] = ApiClient.convertToType(data['discord_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Member</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Member</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['user_url'] && !(typeof data['user_url'] === 'string' || data['user_url'] instanceof String)) {
            throw new Error("Expected the field `user_url` to be a primitive type in the JSON string but got " + data['user_url']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['registered_at'] && !(typeof data['registered_at'] === 'string' || data['registered_at'] instanceof String)) {
            throw new Error("Expected the field `registered_at` to be a primitive type in the JSON string but got " + data['registered_at']);
        }
        // ensure the json data is a string
        if (data['avatar_url_large'] && !(typeof data['avatar_url_large'] === 'string' || data['avatar_url_large'] instanceof String)) {
            throw new Error("Expected the field `avatar_url_large` to be a primitive type in the JSON string but got " + data['avatar_url_large']);
        }
        // ensure the json data is a string
        if (data['avatar_url_medium'] && !(typeof data['avatar_url_medium'] === 'string' || data['avatar_url_medium'] instanceof String)) {
            throw new Error("Expected the field `avatar_url_medium` to be a primitive type in the JSON string but got " + data['avatar_url_medium']);
        }
        // ensure the json data is a string
        if (data['avatar_url_small'] && !(typeof data['avatar_url_small'] === 'string' || data['avatar_url_small'] instanceof String)) {
            throw new Error("Expected the field `avatar_url_small` to be a primitive type in the JSON string but got " + data['avatar_url_small']);
        }
        // ensure the json data is a string
        if (data['discord_id'] && !(typeof data['discord_id'] === 'string' || data['discord_id'] instanceof String)) {
            throw new Error("Expected the field `discord_id` to be a primitive type in the JSON string but got " + data['discord_id']);
        }

        return true;
    }


}



/**
 * @member {String} user_id
 */
Member.prototype['user_id'] = undefined;

/**
 * @member {String} user_url
 */
Member.prototype['user_url'] = undefined;

/**
 * @member {String} username
 */
Member.prototype['username'] = undefined;

/**
 * @member {String} registered_at
 */
Member.prototype['registered_at'] = undefined;

/**
 * @member {String} avatar_url_large
 */
Member.prototype['avatar_url_large'] = undefined;

/**
 * @member {String} avatar_url_medium
 */
Member.prototype['avatar_url_medium'] = undefined;

/**
 * @member {String} avatar_url_small
 */
Member.prototype['avatar_url_small'] = undefined;

/**
 * @member {Boolean} banned
 */
Member.prototype['banned'] = undefined;

/**
 * @member {String} discord_id
 */
Member.prototype['discord_id'] = undefined;






export default Member;

