/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesCreatorCouponsRequest model module.
 * @module model/PostV2ResourcesCreatorCouponsRequest
 * @version v2
 */
class PostV2ResourcesCreatorCouponsRequest {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorCouponsRequest</code>.
     * @alias module:model/PostV2ResourcesCreatorCouponsRequest
     * @param type {String} Must be 'perecent'.
     * @param discount {Number} 
     * @param label {String} The trailing part of the coupon code (without '{user_id}-').
     */
    constructor(type, discount, label) { 
        
        PostV2ResourcesCreatorCouponsRequest.initialize(this, type, discount, label);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, discount, label) { 
        obj['type'] = type;
        obj['discount'] = discount;
        obj['label'] = label;
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorCouponsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorCouponsRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorCouponsRequest} The populated <code>PostV2ResourcesCreatorCouponsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorCouponsRequest();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('do_expiry')) {
                obj['do_expiry'] = ApiClient.convertToType(data['do_expiry'], 'Boolean');
            }
            if (data.hasOwnProperty('expiry_date')) {
                obj['expiry_date'] = ApiClient.convertToType(data['expiry_date'], 'String');
            }
            if (data.hasOwnProperty('limited_uses')) {
                obj['limited_uses'] = ApiClient.convertToType(data['limited_uses'], 'Boolean');
            }
            if (data.hasOwnProperty('max_uses')) {
                obj['max_uses'] = ApiClient.convertToType(data['max_uses'], 'Number');
            }
            if (data.hasOwnProperty('limited_user_uses')) {
                obj['limited_user_uses'] = ApiClient.convertToType(data['limited_user_uses'], 'Boolean');
            }
            if (data.hasOwnProperty('max_per_user_uses')) {
                obj['max_per_user_uses'] = ApiClient.convertToType(data['max_per_user_uses'], 'Number');
            }
            if (data.hasOwnProperty('all_content_types')) {
                obj['all_content_types'] = ApiClient.convertToType(data['all_content_types'], ['String']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], 'String');
            }
            if (data.hasOwnProperty('addons')) {
                obj['addons'] = ApiClient.convertToType(data['addons'], 'String');
            }
            if (data.hasOwnProperty('bundles')) {
                obj['bundles'] = ApiClient.convertToType(data['bundles'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorCouponsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorCouponsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesCreatorCouponsRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['expiry_date'] && !(typeof data['expiry_date'] === 'string' || data['expiry_date'] instanceof String)) {
            throw new Error("Expected the field `expiry_date` to be a primitive type in the JSON string but got " + data['expiry_date']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['all_content_types'])) {
            throw new Error("Expected the field `all_content_types` to be an array in the JSON data but got " + data['all_content_types']);
        }
        // ensure the json data is a string
        if (data['resources'] && !(typeof data['resources'] === 'string' || data['resources'] instanceof String)) {
            throw new Error("Expected the field `resources` to be a primitive type in the JSON string but got " + data['resources']);
        }
        // ensure the json data is a string
        if (data['addons'] && !(typeof data['addons'] === 'string' || data['addons'] instanceof String)) {
            throw new Error("Expected the field `addons` to be a primitive type in the JSON string but got " + data['addons']);
        }
        // ensure the json data is a string
        if (data['bundles'] && !(typeof data['bundles'] === 'string' || data['bundles'] instanceof String)) {
            throw new Error("Expected the field `bundles` to be a primitive type in the JSON string but got " + data['bundles']);
        }

        return true;
    }


}

PostV2ResourcesCreatorCouponsRequest.RequiredProperties = ["type", "discount", "label"];

/**
 * Must be 'perecent'.
 * @member {String} type
 */
PostV2ResourcesCreatorCouponsRequest.prototype['type'] = undefined;

/**
 * @member {Number} discount
 */
PostV2ResourcesCreatorCouponsRequest.prototype['discount'] = undefined;

/**
 * The trailing part of the coupon code (without '{user_id}-').
 * @member {String} label
 */
PostV2ResourcesCreatorCouponsRequest.prototype['label'] = undefined;

/**
 * Whether or not to respect the 'expiry_date' field. No expiry date is set otherwise.
 * @member {Boolean} do_expiry
 */
PostV2ResourcesCreatorCouponsRequest.prototype['do_expiry'] = undefined;

/**
 * @member {String} expiry_date
 */
PostV2ResourcesCreatorCouponsRequest.prototype['expiry_date'] = undefined;

/**
 * Whether or not to respect the 'max_uses' field. No max use limit is set otherwise.
 * @member {Boolean} limited_uses
 */
PostV2ResourcesCreatorCouponsRequest.prototype['limited_uses'] = undefined;

/**
 * @member {Number} max_uses
 */
PostV2ResourcesCreatorCouponsRequest.prototype['max_uses'] = undefined;

/**
 * Whether or not to respect the 'max_per_user_uses' field. No max uses per user limit is set otherwise.
 * @member {Boolean} limited_user_uses
 */
PostV2ResourcesCreatorCouponsRequest.prototype['limited_user_uses'] = undefined;

/**
 * @member {Number} max_per_user_uses
 */
PostV2ResourcesCreatorCouponsRequest.prototype['max_per_user_uses'] = undefined;

/**
 * If a content type is included, all of the creator's content (of that type) can be used against this coupon.  Support values include: 'resource', 'addon', and 'bundle'
 * @member {Array.<String>} all_content_types
 */
PostV2ResourcesCreatorCouponsRequest.prototype['all_content_types'] = undefined;

/**
 * A comma-separated list of resource IDs which this coupon can be used against.
 * @member {String} resources
 */
PostV2ResourcesCreatorCouponsRequest.prototype['resources'] = undefined;

/**
 * A comma-separated list of addon IDs which this coupon can be used against.
 * @member {String} addons
 */
PostV2ResourcesCreatorCouponsRequest.prototype['addons'] = undefined;

/**
 * A comma-separated list of bundle IDs which this coupon can be used against.
 * @member {String} bundles
 */
PostV2ResourcesCreatorCouponsRequest.prototype['bundles'] = undefined;






export default PostV2ResourcesCreatorCouponsRequest;

