/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesEmbedDownloadRequest model module.
 * @module model/PostV2ResourcesEmbedDownloadRequest
 * @version v2
 */
class PostV2ResourcesEmbedDownloadRequest {
    /**
     * Constructs a new <code>PostV2ResourcesEmbedDownloadRequest</code>.
     * @alias module:model/PostV2ResourcesEmbedDownloadRequest
     * @param nonce {String} 
     * @param contentType {String} 
     * @param contentId {Number} 
     */
    constructor(nonce, contentType, contentId) { 
        
        PostV2ResourcesEmbedDownloadRequest.initialize(this, nonce, contentType, contentId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nonce, contentType, contentId) { 
        obj['nonce'] = nonce;
        obj['content_type'] = contentType;
        obj['content_id'] = contentId;
    }

    /**
     * Constructs a <code>PostV2ResourcesEmbedDownloadRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesEmbedDownloadRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesEmbedDownloadRequest} The populated <code>PostV2ResourcesEmbedDownloadRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesEmbedDownloadRequest();

            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('content_id')) {
                obj['content_id'] = ApiClient.convertToType(data['content_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesEmbedDownloadRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesEmbedDownloadRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesEmbedDownloadRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nonce'] && !(typeof data['nonce'] === 'string' || data['nonce'] instanceof String)) {
            throw new Error("Expected the field `nonce` to be a primitive type in the JSON string but got " + data['nonce']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }

        return true;
    }


}

PostV2ResourcesEmbedDownloadRequest.RequiredProperties = ["nonce", "content_type", "content_id"];

/**
 * @member {String} nonce
 */
PostV2ResourcesEmbedDownloadRequest.prototype['nonce'] = undefined;

/**
 * @member {String} content_type
 */
PostV2ResourcesEmbedDownloadRequest.prototype['content_type'] = undefined;

/**
 * @member {Number} content_id
 */
PostV2ResourcesEmbedDownloadRequest.prototype['content_id'] = undefined;






export default PostV2ResourcesEmbedDownloadRequest;

