/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Batch from './Batch';

/**
 * The PostV2ResourcesCreatorBatch200ResponseData model module.
 * @module model/PostV2ResourcesCreatorBatch200ResponseData
 * @version v2
 */
class PostV2ResourcesCreatorBatch200ResponseData {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorBatch200ResponseData</code>.
     * @alias module:model/PostV2ResourcesCreatorBatch200ResponseData
     */
    constructor() { 
        
        PostV2ResourcesCreatorBatch200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorBatch200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorBatch200ResponseData} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorBatch200ResponseData} The populated <code>PostV2ResourcesCreatorBatch200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorBatch200ResponseData();

            if (data.hasOwnProperty('batch')) {
                obj['batch'] = Batch.constructFromObject(data['batch']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorBatch200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorBatch200ResponseData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `batch`
        if (data['batch']) { // data not null
          Batch.validateJSON(data['batch']);
        }

        return true;
    }


}



/**
 * @member {module:model/Batch} batch
 */
PostV2ResourcesCreatorBatch200ResponseData.prototype['batch'] = undefined;






export default PostV2ResourcesCreatorBatch200ResponseData;

