/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2ResourcesDiscoverCartCheckout200ResponseData from './PostV2ResourcesDiscoverCartCheckout200ResponseData';

/**
 * The PostV2ResourcesDiscoverCartCheckout200Response model module.
 * @module model/PostV2ResourcesDiscoverCartCheckout200Response
 * @version v2
 */
class PostV2ResourcesDiscoverCartCheckout200Response {
    /**
     * Constructs a new <code>PostV2ResourcesDiscoverCartCheckout200Response</code>.
     * @alias module:model/PostV2ResourcesDiscoverCartCheckout200Response
     * @param result {module:model/PostV2ResourcesDiscoverCartCheckout200Response.ResultEnum} 
     * @param data {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData} 
     */
    constructor(result, data) { 
        
        PostV2ResourcesDiscoverCartCheckout200Response.initialize(this, result, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result, data) { 
        obj['result'] = result;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>PostV2ResourcesDiscoverCartCheckout200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesDiscoverCartCheckout200Response} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesDiscoverCartCheckout200Response} The populated <code>PostV2ResourcesDiscoverCartCheckout200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesDiscoverCartCheckout200Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = PostV2ResourcesDiscoverCartCheckout200ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesDiscoverCartCheckout200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesDiscoverCartCheckout200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesDiscoverCartCheckout200Response.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          PostV2ResourcesDiscoverCartCheckout200ResponseData.validateJSON(data['data']);
        }

        return true;
    }


}

PostV2ResourcesDiscoverCartCheckout200Response.RequiredProperties = ["result", "data"];

/**
 * @member {module:model/PostV2ResourcesDiscoverCartCheckout200Response.ResultEnum} result
 */
PostV2ResourcesDiscoverCartCheckout200Response.prototype['result'] = undefined;

/**
 * @member {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData} data
 */
PostV2ResourcesDiscoverCartCheckout200Response.prototype['data'] = undefined;





/**
 * Allowed values for the <code>result</code> property.
 * @enum {String}
 * @readonly
 */
PostV2ResourcesDiscoverCartCheckout200Response['ResultEnum'] = {

    /**
     * value: "success"
     * @const
     */
    "success": "success"
};



export default PostV2ResourcesDiscoverCartCheckout200Response;

