/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2DeploymentsUpgradeRequest model module.
 * @module model/PostV2DeploymentsUpgradeRequest
 * @version v2
 */
class PostV2DeploymentsUpgradeRequest {
    /**
     * Constructs a new <code>PostV2DeploymentsUpgradeRequest</code>.
     * @alias module:model/PostV2DeploymentsUpgradeRequest
     */
    constructor() { 
        
        PostV2DeploymentsUpgradeRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2DeploymentsUpgradeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2DeploymentsUpgradeRequest} obj Optional instance to populate.
     * @return {module:model/PostV2DeploymentsUpgradeRequest} The populated <code>PostV2DeploymentsUpgradeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2DeploymentsUpgradeRequest();

            if (data.hasOwnProperty('preauthorize')) {
                obj['preauthorize'] = ApiClient.convertToType(data['preauthorize'], 'Boolean');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2DeploymentsUpgradeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2DeploymentsUpgradeRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['scopes'] && !(typeof data['scopes'] === 'string' || data['scopes'] instanceof String)) {
            throw new Error("Expected the field `scopes` to be a primitive type in the JSON string but got " + data['scopes']);
        }

        return true;
    }


}



/**
 * Whether or not to pre-authorize OAuth2 credentials for the deployment token owner.
 * @member {Boolean} preauthorize
 * @default false
 */
PostV2DeploymentsUpgradeRequest.prototype['preauthorize'] = false;

/**
 * A space-separated list of scopes to request if pre-authorizing.
 * @member {String} scopes
 */
PostV2DeploymentsUpgradeRequest.prototype['scopes'] = undefined;






export default PostV2DeploymentsUpgradeRequest;

