/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2DeploymentsUpgrade200ResponseDataPreauthorize from './PostV2DeploymentsUpgrade200ResponseDataPreauthorize';

/**
 * The PostV2DeploymentsUpgrade200ResponseData model module.
 * @module model/PostV2DeploymentsUpgrade200ResponseData
 * @version v2
 */
class PostV2DeploymentsUpgrade200ResponseData {
    /**
     * Constructs a new <code>PostV2DeploymentsUpgrade200ResponseData</code>.
     * @alias module:model/PostV2DeploymentsUpgrade200ResponseData
     */
    constructor() { 
        
        PostV2DeploymentsUpgrade200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2DeploymentsUpgrade200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2DeploymentsUpgrade200ResponseData} obj Optional instance to populate.
     * @return {module:model/PostV2DeploymentsUpgrade200ResponseData} The populated <code>PostV2DeploymentsUpgrade200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2DeploymentsUpgrade200ResponseData();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('oauth2_client')) {
                obj['oauth2_client'] = ApiClient.convertToType(data['oauth2_client'], 'String');
            }
            if (data.hasOwnProperty('oauth2_secret')) {
                obj['oauth2_secret'] = ApiClient.convertToType(data['oauth2_secret'], 'String');
            }
            if (data.hasOwnProperty('preauthorize')) {
                obj['preauthorize'] = PostV2DeploymentsUpgrade200ResponseDataPreauthorize.constructFromObject(data['preauthorize']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2DeploymentsUpgrade200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2DeploymentsUpgrade200ResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['oauth2_client'] && !(typeof data['oauth2_client'] === 'string' || data['oauth2_client'] instanceof String)) {
            throw new Error("Expected the field `oauth2_client` to be a primitive type in the JSON string but got " + data['oauth2_client']);
        }
        // ensure the json data is a string
        if (data['oauth2_secret'] && !(typeof data['oauth2_secret'] === 'string' || data['oauth2_secret'] instanceof String)) {
            throw new Error("Expected the field `oauth2_secret` to be a primitive type in the JSON string but got " + data['oauth2_secret']);
        }
        // validate the optional field `preauthorize`
        if (data['preauthorize']) { // data not null
          PostV2DeploymentsUpgrade200ResponseDataPreauthorize.validateJSON(data['preauthorize']);
        }

        return true;
    }


}



/**
 * @member {String} token
 */
PostV2DeploymentsUpgrade200ResponseData.prototype['token'] = undefined;

/**
 * @member {String} oauth2_client
 */
PostV2DeploymentsUpgrade200ResponseData.prototype['oauth2_client'] = undefined;

/**
 * @member {String} oauth2_secret
 */
PostV2DeploymentsUpgrade200ResponseData.prototype['oauth2_secret'] = undefined;

/**
 * @member {module:model/PostV2DeploymentsUpgrade200ResponseDataPreauthorize} preauthorize
 */
PostV2DeploymentsUpgrade200ResponseData.prototype['preauthorize'] = undefined;






export default PostV2DeploymentsUpgrade200ResponseData;

