/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2DeploymentsUpgrade200ResponseData from './PostV2DeploymentsUpgrade200ResponseData';

/**
 * The PostV2DeploymentsUpgrade200Response model module.
 * @module model/PostV2DeploymentsUpgrade200Response
 * @version v2
 */
class PostV2DeploymentsUpgrade200Response {
    /**
     * Constructs a new <code>PostV2DeploymentsUpgrade200Response</code>.
     * @alias module:model/PostV2DeploymentsUpgrade200Response
     */
    constructor() { 
        
        PostV2DeploymentsUpgrade200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2DeploymentsUpgrade200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2DeploymentsUpgrade200Response} obj Optional instance to populate.
     * @return {module:model/PostV2DeploymentsUpgrade200Response} The populated <code>PostV2DeploymentsUpgrade200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2DeploymentsUpgrade200Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = PostV2DeploymentsUpgrade200ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2DeploymentsUpgrade200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2DeploymentsUpgrade200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          PostV2DeploymentsUpgrade200ResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostV2DeploymentsUpgrade200Response.ResultEnum} result
 */
PostV2DeploymentsUpgrade200Response.prototype['result'] = undefined;

/**
 * @member {module:model/PostV2DeploymentsUpgrade200ResponseData} data
 */
PostV2DeploymentsUpgrade200Response.prototype['data'] = undefined;





/**
 * Allowed values for the <code>result</code> property.
 * @enum {String}
 * @readonly
 */
PostV2DeploymentsUpgrade200Response['ResultEnum'] = {

    /**
     * value: "success"
     * @const
     */
    "success": "success"
};



export default PostV2DeploymentsUpgrade200Response;

