/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2ResourcesCreatorAddonsUpdateRequestFile from './PostV2ResourcesCreatorAddonsUpdateRequestFile';

/**
 * The PostV2ResourcesCreatorAddonsUpdateRequest model module.
 * @module model/PostV2ResourcesCreatorAddonsUpdateRequest
 * @version v2
 */
class PostV2ResourcesCreatorAddonsUpdateRequest {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorAddonsUpdateRequest</code>.
     * @alias module:model/PostV2ResourcesCreatorAddonsUpdateRequest
     * @param addonId {Number} 
     * @param file {module:model/PostV2ResourcesCreatorAddonsUpdateRequestFile} 
     * @param versionName {String} 
     */
    constructor(addonId, file, versionName) { 
        
        PostV2ResourcesCreatorAddonsUpdateRequest.initialize(this, addonId, file, versionName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, addonId, file, versionName) { 
        obj['addon_id'] = addonId;
        obj['file'] = file;
        obj['version_name'] = versionName;
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorAddonsUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorAddonsUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorAddonsUpdateRequest} The populated <code>PostV2ResourcesCreatorAddonsUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorAddonsUpdateRequest();

            if (data.hasOwnProperty('addon_id')) {
                obj['addon_id'] = ApiClient.convertToType(data['addon_id'], 'Number');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = PostV2ResourcesCreatorAddonsUpdateRequestFile.constructFromObject(data['file']);
            }
            if (data.hasOwnProperty('version_name')) {
                obj['version_name'] = ApiClient.convertToType(data['version_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorAddonsUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorAddonsUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesCreatorAddonsUpdateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `file`
        if (data['file']) { // data not null
          PostV2ResourcesCreatorAddonsUpdateRequestFile.validateJSON(data['file']);
        }
        // ensure the json data is a string
        if (data['version_name'] && !(typeof data['version_name'] === 'string' || data['version_name'] instanceof String)) {
            throw new Error("Expected the field `version_name` to be a primitive type in the JSON string but got " + data['version_name']);
        }

        return true;
    }


}

PostV2ResourcesCreatorAddonsUpdateRequest.RequiredProperties = ["addon_id", "file", "version_name"];

/**
 * @member {Number} addon_id
 */
PostV2ResourcesCreatorAddonsUpdateRequest.prototype['addon_id'] = undefined;

/**
 * @member {module:model/PostV2ResourcesCreatorAddonsUpdateRequestFile} file
 */
PostV2ResourcesCreatorAddonsUpdateRequest.prototype['file'] = undefined;

/**
 * @member {String} version_name
 */
PostV2ResourcesCreatorAddonsUpdateRequest.prototype['version_name'] = undefined;






export default PostV2ResourcesCreatorAddonsUpdateRequest;

