/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesDiscoverCartAddRequest model module.
 * @module model/PostV2ResourcesDiscoverCartAddRequest
 * @version v2
 */
class PostV2ResourcesDiscoverCartAddRequest {
    /**
     * Constructs a new <code>PostV2ResourcesDiscoverCartAddRequest</code>.
     * @alias module:model/PostV2ResourcesDiscoverCartAddRequest
     */
    constructor() { 
        
        PostV2ResourcesDiscoverCartAddRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2ResourcesDiscoverCartAddRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesDiscoverCartAddRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesDiscoverCartAddRequest} The populated <code>PostV2ResourcesDiscoverCartAddRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesDiscoverCartAddRequest();

            if (data.hasOwnProperty('add')) {
                obj['add'] = ApiClient.convertToType(data['add'], [['Number']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesDiscoverCartAddRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesDiscoverCartAddRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['add'])) {
            throw new Error("Expected the field `add` to be an array in the JSON data but got " + data['add']);
        }

        return true;
    }


}



/**
 * @member {Array.<Array.<Number>>} add
 */
PostV2ResourcesDiscoverCartAddRequest.prototype['add'] = undefined;






export default PostV2ResourcesDiscoverCartAddRequest;

