/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesCreatorUpdateRequestUpdate model module.
 * @module model/PostV2ResourcesCreatorUpdateRequestUpdate
 * @version v2
 */
class PostV2ResourcesCreatorUpdateRequestUpdate {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorUpdateRequestUpdate</code>.
     * @alias module:model/PostV2ResourcesCreatorUpdateRequestUpdate
     */
    constructor() { 
        
        PostV2ResourcesCreatorUpdateRequestUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorUpdateRequestUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorUpdateRequestUpdate} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorUpdateRequestUpdate} The populated <code>PostV2ResourcesCreatorUpdateRequestUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorUpdateRequestUpdate();

            if (data.hasOwnProperty('post')) {
                obj['post'] = ApiClient.convertToType(data['post'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorUpdateRequestUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorUpdateRequestUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * Whether or not to post an update alongside the new version.
 * @member {Boolean} post
 */
PostV2ResourcesCreatorUpdateRequestUpdate.prototype['post'] = undefined;

/**
 * @member {String} title
 */
PostV2ResourcesCreatorUpdateRequestUpdate.prototype['title'] = undefined;

/**
 * The BBCode-formatted body of the update.
 * @member {String} message
 */
PostV2ResourcesCreatorUpdateRequestUpdate.prototype['message'] = undefined;






export default PostV2ResourcesCreatorUpdateRequestUpdate;

