/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesDiscoverCartCouponRemoveRequest model module.
 * @module model/PostV2ResourcesDiscoverCartCouponRemoveRequest
 * @version v2
 */
class PostV2ResourcesDiscoverCartCouponRemoveRequest {
    /**
     * Constructs a new <code>PostV2ResourcesDiscoverCartCouponRemoveRequest</code>.
     * @alias module:model/PostV2ResourcesDiscoverCartCouponRemoveRequest
     */
    constructor() { 
        
        PostV2ResourcesDiscoverCartCouponRemoveRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2ResourcesDiscoverCartCouponRemoveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesDiscoverCartCouponRemoveRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesDiscoverCartCouponRemoveRequest} The populated <code>PostV2ResourcesDiscoverCartCouponRemoveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesDiscoverCartCouponRemoveRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesDiscoverCartCouponRemoveRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesDiscoverCartCouponRemoveRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}



/**
 * @member {String} code
 */
PostV2ResourcesDiscoverCartCouponRemoveRequest.prototype['code'] = undefined;






export default PostV2ResourcesDiscoverCartCouponRemoveRequest;

