/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2ResourcesCreatorApiAssetsUpdateRequestFile from './PostV2ResourcesCreatorApiAssetsUpdateRequestFile';

/**
 * The PostV2ResourcesCreatorApiAssetsUpdateRequest model module.
 * @module model/PostV2ResourcesCreatorApiAssetsUpdateRequest
 * @version v2
 */
class PostV2ResourcesCreatorApiAssetsUpdateRequest {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorApiAssetsUpdateRequest</code>.
     * @alias module:model/PostV2ResourcesCreatorApiAssetsUpdateRequest
     * @param apiAssetId {String} 
     * @param file {module:model/PostV2ResourcesCreatorApiAssetsUpdateRequestFile} 
     */
    constructor(apiAssetId, file) { 
        
        PostV2ResourcesCreatorApiAssetsUpdateRequest.initialize(this, apiAssetId, file);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiAssetId, file) { 
        obj['api_asset_id'] = apiAssetId;
        obj['file'] = file;
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorApiAssetsUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorApiAssetsUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorApiAssetsUpdateRequest} The populated <code>PostV2ResourcesCreatorApiAssetsUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorApiAssetsUpdateRequest();

            if (data.hasOwnProperty('api_asset_id')) {
                obj['api_asset_id'] = ApiClient.convertToType(data['api_asset_id'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = PostV2ResourcesCreatorApiAssetsUpdateRequestFile.constructFromObject(data['file']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorApiAssetsUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorApiAssetsUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesCreatorApiAssetsUpdateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['api_asset_id'] && !(typeof data['api_asset_id'] === 'string' || data['api_asset_id'] instanceof String)) {
            throw new Error("Expected the field `api_asset_id` to be a primitive type in the JSON string but got " + data['api_asset_id']);
        }
        // validate the optional field `file`
        if (data['file']) { // data not null
          PostV2ResourcesCreatorApiAssetsUpdateRequestFile.validateJSON(data['file']);
        }

        return true;
    }


}

PostV2ResourcesCreatorApiAssetsUpdateRequest.RequiredProperties = ["api_asset_id", "file"];

/**
 * @member {String} api_asset_id
 */
PostV2ResourcesCreatorApiAssetsUpdateRequest.prototype['api_asset_id'] = undefined;

/**
 * @member {module:model/PostV2ResourcesCreatorApiAssetsUpdateRequestFile} file
 */
PostV2ResourcesCreatorApiAssetsUpdateRequest.prototype['file'] = undefined;






export default PostV2ResourcesCreatorApiAssetsUpdateRequest;

