/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV2ResourcesCreatorBatchRequestChangesInner from './PostV2ResourcesCreatorBatchRequestChangesInner';

/**
 * The PostV2ResourcesCreatorBatchRequest model module.
 * @module model/PostV2ResourcesCreatorBatchRequest
 * @version v2
 */
class PostV2ResourcesCreatorBatchRequest {
    /**
     * Constructs a new <code>PostV2ResourcesCreatorBatchRequest</code>.
     * @alias module:model/PostV2ResourcesCreatorBatchRequest
     * @param resources {Array.<Object>} A list of resource IDs to edit.
     * @param changes {Array.<module:model/PostV2ResourcesCreatorBatchRequestChangesInner>} 
     */
    constructor(resources, changes) { 
        
        PostV2ResourcesCreatorBatchRequest.initialize(this, resources, changes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resources, changes) { 
        obj['resources'] = resources;
        obj['changes'] = changes;
    }

    /**
     * Constructs a <code>PostV2ResourcesCreatorBatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesCreatorBatchRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesCreatorBatchRequest} The populated <code>PostV2ResourcesCreatorBatchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesCreatorBatchRequest();

            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], [Object]);
            }
            if (data.hasOwnProperty('changes')) {
                obj['changes'] = ApiClient.convertToType(data['changes'], [PostV2ResourcesCreatorBatchRequestChangesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesCreatorBatchRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesCreatorBatchRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesCreatorBatchRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['resources'])) {
            throw new Error("Expected the field `resources` to be an array in the JSON data but got " + data['resources']);
        }
        if (data['changes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['changes'])) {
                throw new Error("Expected the field `changes` to be an array in the JSON data but got " + data['changes']);
            }
            // validate the optional field `changes` (array)
            for (const item of data['changes']) {
                PostV2ResourcesCreatorBatchRequestChangesInner.validateJSON(item);
            };
        }

        return true;
    }


}

PostV2ResourcesCreatorBatchRequest.RequiredProperties = ["resources", "changes"];

/**
 * A list of resource IDs to edit.
 * @member {Array.<Object>} resources
 */
PostV2ResourcesCreatorBatchRequest.prototype['resources'] = undefined;

/**
 * @member {Array.<module:model/PostV2ResourcesCreatorBatchRequestChangesInner>} changes
 */
PostV2ResourcesCreatorBatchRequest.prototype['changes'] = undefined;






export default PostV2ResourcesCreatorBatchRequest;

