/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesDiscoverCartCheckout200ResponseData model module.
 * @module model/PostV2ResourcesDiscoverCartCheckout200ResponseData
 * @version v2
 */
class PostV2ResourcesDiscoverCartCheckout200ResponseData {
    /**
     * Constructs a new <code>PostV2ResourcesDiscoverCartCheckout200ResponseData</code>.
     * @alias module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData
     * @param status {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData.StatusEnum} `initiated` - the checkout request was successful and returned a Tebex basket identifier stored in the `ident` field.    `bypassed` - the checkout was successful but no Tebex basket identifier was generated as it was not needed (perhaps because the buyer used a 100% off coupon).
     */
    constructor(status) { 
        
        PostV2ResourcesDiscoverCartCheckout200ResponseData.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PostV2ResourcesDiscoverCartCheckout200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData} The populated <code>PostV2ResourcesDiscoverCartCheckout200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesDiscoverCartCheckout200ResponseData();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('ident')) {
                obj['ident'] = ApiClient.convertToType(data['ident'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesDiscoverCartCheckout200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesDiscoverCartCheckout200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV2ResourcesDiscoverCartCheckout200ResponseData.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['ident'] && !(typeof data['ident'] === 'string' || data['ident'] instanceof String)) {
            throw new Error("Expected the field `ident` to be a primitive type in the JSON string but got " + data['ident']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

PostV2ResourcesDiscoverCartCheckout200ResponseData.RequiredProperties = ["status"];

/**
 * `initiated` - the checkout request was successful and returned a Tebex basket identifier stored in the `ident` field.    `bypassed` - the checkout was successful but no Tebex basket identifier was generated as it was not needed (perhaps because the buyer used a 100% off coupon).
 * @member {module:model/PostV2ResourcesDiscoverCartCheckout200ResponseData.StatusEnum} status
 */
PostV2ResourcesDiscoverCartCheckout200ResponseData.prototype['status'] = undefined;

/**
 * The Tebex cart identifier which you can use to redirect to or open a Tebex.js overlay.
 * @member {String} ident
 */
PostV2ResourcesDiscoverCartCheckout200ResponseData.prototype['ident'] = undefined;

/**
 * The Tebex checkout link to redirect to if not using Tebex.js (built from the included ident).
 * @member {String} url
 */
PostV2ResourcesDiscoverCartCheckout200ResponseData.prototype['url'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PostV2ResourcesDiscoverCartCheckout200ResponseData['StatusEnum'] = {

    /**
     * value: "initiated"
     * @const
     */
    "initiated": "initiated",

    /**
     * value: "bypassed"
     * @const
     */
    "bypassed": "bypassed"
};



export default PostV2ResourcesDiscoverCartCheckout200ResponseData;

