/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV2ResourcesDiscoverCartRemoveRequest model module.
 * @module model/PostV2ResourcesDiscoverCartRemoveRequest
 * @version v2
 */
class PostV2ResourcesDiscoverCartRemoveRequest {
    /**
     * Constructs a new <code>PostV2ResourcesDiscoverCartRemoveRequest</code>.
     * @alias module:model/PostV2ResourcesDiscoverCartRemoveRequest
     */
    constructor() { 
        
        PostV2ResourcesDiscoverCartRemoveRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV2ResourcesDiscoverCartRemoveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV2ResourcesDiscoverCartRemoveRequest} obj Optional instance to populate.
     * @return {module:model/PostV2ResourcesDiscoverCartRemoveRequest} The populated <code>PostV2ResourcesDiscoverCartRemoveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV2ResourcesDiscoverCartRemoveRequest();

            if (data.hasOwnProperty('cart_item_id')) {
                obj['cart_item_id'] = ApiClient.convertToType(data['cart_item_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV2ResourcesDiscoverCartRemoveRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV2ResourcesDiscoverCartRemoveRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} cart_item_id
 */
PostV2ResourcesDiscoverCartRemoveRequest.prototype['cart_item_id'] = undefined;






export default PostV2ResourcesDiscoverCartRemoveRequest;

