/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Addon from './Addon';
import Category from './Category';
import Description from './Description';
import Member from './Member';
import Review from './Review';
import SaleEventEntry from './SaleEventEntry';
import Version from './Version';

/**
 * The Resource model module.
 * @module model/Resource
 * @version v2
 */
class Resource {
    /**
     * Constructs a new <code>Resource</code>.
     * Supported &#39;with&#39; values: - &#39;Creator&#39;: the resource creator/owner - &#39;Category&#39;: the resource category  - &#39;Description&#39;: the resource description (rendered HTML and BBCode) - &#39;LatestReviews&#39;: list of the 10 latest reviews - &#39;Filter values&#39;: filter values set by the creator
     * @alias module:model/Resource
     */
    constructor() { 
        
        Resource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Resource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Resource} obj Optional instance to populate.
     * @return {module:model/Resource} The populated <code>Resource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Resource();

            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('creator_id')) {
                obj['creator_id'] = ApiClient.convertToType(data['creator_id'], 'Number');
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Number');
            }
            if (data.hasOwnProperty('last_updated_at')) {
                obj['last_updated_at'] = ApiClient.convertToType(data['last_updated_at'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('purchases')) {
                obj['purchases'] = ApiClient.convertToType(data['purchases'], 'Number');
            }
            if (data.hasOwnProperty('downloads')) {
                obj['downloads'] = ApiClient.convertToType(data['downloads'], 'Number');
            }
            if (data.hasOwnProperty('list_price')) {
                obj['list_price'] = ApiClient.convertToType(data['list_price'], 'Number');
            }
            if (data.hasOwnProperty('cover_image_url')) {
                obj['cover_image_url'] = ApiClient.convertToType(data['cover_image_url'], 'String');
            }
            if (data.hasOwnProperty('final_price')) {
                obj['final_price'] = ApiClient.convertToType(data['final_price'], 'Number');
            }
            if (data.hasOwnProperty('final_price_formatted')) {
                obj['final_price_formatted'] = ApiClient.convertToType(data['final_price_formatted'], 'String');
            }
            if (data.hasOwnProperty('list_price_formatted')) {
                obj['list_price_formatted'] = ApiClient.convertToType(data['list_price_formatted'], 'String');
            }
            if (data.hasOwnProperty('carousel_image_urls')) {
                obj['carousel_image_urls'] = ApiClient.convertToType(data['carousel_image_urls'], ['String']);
            }
            if (data.hasOwnProperty('review_count')) {
                obj['review_count'] = ApiClient.convertToType(data['review_count'], 'Number');
            }
            if (data.hasOwnProperty('review_average')) {
                obj['review_average'] = ApiClient.convertToType(data['review_average'], 'Number');
            }
            if (data.hasOwnProperty('SaleEventEntry')) {
                obj['SaleEventEntry'] = SaleEventEntry.constructFromObject(data['SaleEventEntry']);
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = Member.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('LatestVersion')) {
                obj['LatestVersion'] = Version.constructFromObject(data['LatestVersion']);
            }
            if (data.hasOwnProperty('LatestUpdate')) {
                obj['LatestUpdate'] = Version.constructFromObject(data['LatestUpdate']);
            }
            if (data.hasOwnProperty('LatestReviews')) {
                obj['LatestReviews'] = ApiClient.convertToType(data['LatestReviews'], [Review]);
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = Description.constructFromObject(data['Description']);
            }
            if (data.hasOwnProperty('Category')) {
                obj['Category'] = Category.constructFromObject(data['Category']);
            }
            if (data.hasOwnProperty('Addons')) {
                obj['Addons'] = ApiClient.convertToType(data['Addons'], {'String': [Addon]});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Resource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Resource</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['cover_image_url'] && !(typeof data['cover_image_url'] === 'string' || data['cover_image_url'] instanceof String)) {
            throw new Error("Expected the field `cover_image_url` to be a primitive type in the JSON string but got " + data['cover_image_url']);
        }
        // ensure the json data is a string
        if (data['final_price_formatted'] && !(typeof data['final_price_formatted'] === 'string' || data['final_price_formatted'] instanceof String)) {
            throw new Error("Expected the field `final_price_formatted` to be a primitive type in the JSON string but got " + data['final_price_formatted']);
        }
        // ensure the json data is a string
        if (data['list_price_formatted'] && !(typeof data['list_price_formatted'] === 'string' || data['list_price_formatted'] instanceof String)) {
            throw new Error("Expected the field `list_price_formatted` to be a primitive type in the JSON string but got " + data['list_price_formatted']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['carousel_image_urls'])) {
            throw new Error("Expected the field `carousel_image_urls` to be an array in the JSON data but got " + data['carousel_image_urls']);
        }
        // validate the optional field `SaleEventEntry`
        if (data['SaleEventEntry']) { // data not null
          SaleEventEntry.validateJSON(data['SaleEventEntry']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          Member.validateJSON(data['Creator']);
        }
        // validate the optional field `LatestVersion`
        if (data['LatestVersion']) { // data not null
          Version.validateJSON(data['LatestVersion']);
        }
        // validate the optional field `LatestUpdate`
        if (data['LatestUpdate']) { // data not null
          Version.validateJSON(data['LatestUpdate']);
        }
        if (data['LatestReviews']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['LatestReviews'])) {
                throw new Error("Expected the field `LatestReviews` to be an array in the JSON data but got " + data['LatestReviews']);
            }
            // validate the optional field `LatestReviews` (array)
            for (const item of data['LatestReviews']) {
                Review.validateJSON(item);
            };
        }
        // validate the optional field `Description`
        if (data['Description']) { // data not null
          Description.validateJSON(data['Description']);
        }
        // validate the optional field `Category`
        if (data['Category']) { // data not null
          Category.validateJSON(data['Category']);
        }

        return true;
    }


}



/**
 * @member {Number} resource_id
 */
Resource.prototype['resource_id'] = undefined;

/**
 * @member {String} title
 */
Resource.prototype['title'] = undefined;

/**
 * @member {String} summary
 */
Resource.prototype['summary'] = undefined;

/**
 * @member {String} url
 */
Resource.prototype['url'] = undefined;

/**
 * @member {Number} creator_id
 */
Resource.prototype['creator_id'] = undefined;

/**
 * @member {Number} published_at
 */
Resource.prototype['published_at'] = undefined;

/**
 * @member {Number} last_updated_at
 */
Resource.prototype['last_updated_at'] = undefined;

/**
 * @member {String} currency
 */
Resource.prototype['currency'] = undefined;

/**
 * @member {Number} purchases
 */
Resource.prototype['purchases'] = undefined;

/**
 * @member {Number} downloads
 */
Resource.prototype['downloads'] = undefined;

/**
 * @member {Number} list_price
 */
Resource.prototype['list_price'] = undefined;

/**
 * @member {String} cover_image_url
 */
Resource.prototype['cover_image_url'] = undefined;

/**
 * @member {Number} final_price
 */
Resource.prototype['final_price'] = undefined;

/**
 * @member {String} final_price_formatted
 */
Resource.prototype['final_price_formatted'] = undefined;

/**
 * @member {String} list_price_formatted
 */
Resource.prototype['list_price_formatted'] = undefined;

/**
 * @member {Array.<String>} carousel_image_urls
 */
Resource.prototype['carousel_image_urls'] = undefined;

/**
 * @member {Number} review_count
 */
Resource.prototype['review_count'] = undefined;

/**
 * @member {Number} review_average
 */
Resource.prototype['review_average'] = undefined;

/**
 * @member {module:model/SaleEventEntry} SaleEventEntry
 */
Resource.prototype['SaleEventEntry'] = undefined;

/**
 * @member {module:model/Member} Creator
 */
Resource.prototype['Creator'] = undefined;

/**
 * @member {module:model/Version} LatestVersion
 */
Resource.prototype['LatestVersion'] = undefined;

/**
 * @member {module:model/Version} LatestUpdate
 */
Resource.prototype['LatestUpdate'] = undefined;

/**
 * @member {Array.<module:model/Review>} LatestReviews
 */
Resource.prototype['LatestReviews'] = undefined;

/**
 * @member {module:model/Description} Description
 */
Resource.prototype['Description'] = undefined;

/**
 * @member {module:model/Category} Category
 */
Resource.prototype['Category'] = undefined;

/**
 * @member {Object.<String, Array.<module:model/Addon>>} Addons
 */
Resource.prototype['Addons'] = undefined;






export default Resource;

