/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Review model module.
 * @module model/Review
 * @version v2
 */
class Review {
    /**
     * Constructs a new <code>Review</code>.
     * @alias module:model/Review
     */
    constructor() { 
        
        Review.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Review</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Review} obj Optional instance to populate.
     * @return {module:model/Review} The populated <code>Review</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Review();

            if (data.hasOwnProperty('review_id')) {
                obj['review_id'] = ApiClient.convertToType(data['review_id'], 'String');
            }
            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'String');
            }
            if (data.hasOwnProperty('reviewer_id')) {
                obj['reviewer_id'] = ApiClient.convertToType(data['reviewer_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Review</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Review</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['review_id'] && !(typeof data['review_id'] === 'string' || data['review_id'] instanceof String)) {
            throw new Error("Expected the field `review_id` to be a primitive type in the JSON string but got " + data['review_id']);
        }
        // ensure the json data is a string
        if (data['resource_id'] && !(typeof data['resource_id'] === 'string' || data['resource_id'] instanceof String)) {
            throw new Error("Expected the field `resource_id` to be a primitive type in the JSON string but got " + data['resource_id']);
        }
        // ensure the json data is a string
        if (data['reviewer_id'] && !(typeof data['reviewer_id'] === 'string' || data['reviewer_id'] instanceof String)) {
            throw new Error("Expected the field `reviewer_id` to be a primitive type in the JSON string but got " + data['reviewer_id']);
        }

        return true;
    }


}



/**
 * @member {String} review_id
 */
Review.prototype['review_id'] = undefined;

/**
 * @member {String} resource_id
 */
Review.prototype['resource_id'] = undefined;

/**
 * @member {String} reviewer_id
 */
Review.prototype['reviewer_id'] = undefined;






export default Review;

