/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Resource from './Resource';
import RichText from './RichText';

/**
 * The Update model module.
 * @module model/Update
 * @version v2
 */
class Update {
    /**
     * Constructs a new <code>Update</code>.
     * Supported &#39;with&#39; hints: - &#39;Resource&#39;: the resource this update relates to - &#39;Description&#39;: the rendered description of the update
     * @alias module:model/Update
     */
    constructor() { 
        
        Update.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Update</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Update} obj Optional instance to populate.
     * @return {module:model/Update} The populated <code>Update</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Update();

            if (data.hasOwnProperty('update_id')) {
                obj['update_id'] = ApiClient.convertToType(data['update_id'], 'Number');
            }
            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = RichText.constructFromObject(data['Description']);
            }
            if (data.hasOwnProperty('Resource')) {
                obj['Resource'] = Resource.constructFromObject(data['Resource']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Update</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Update</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // validate the optional field `Description`
        if (data['Description']) { // data not null
          RichText.validateJSON(data['Description']);
        }
        // validate the optional field `Resource`
        if (data['Resource']) { // data not null
          Resource.validateJSON(data['Resource']);
        }

        return true;
    }


}



/**
 * @member {Number} update_id
 */
Update.prototype['update_id'] = undefined;

/**
 * @member {Number} resource_id
 */
Update.prototype['resource_id'] = undefined;

/**
 * @member {Number} created_at
 */
Update.prototype['created_at'] = undefined;

/**
 * @member {String} title
 */
Update.prototype['title'] = undefined;

/**
 * @member {module:model/RichText} Description
 */
Update.prototype['Description'] = undefined;

/**
 * @member {module:model/Resource} Resource
 */
Update.prototype['Resource'] = undefined;






export default Update;

