/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2Analytics200Response from '../model/GetV2Analytics200Response';
import GetV2AnalyticsGraph200Response from '../model/GetV2AnalyticsGraph200Response';
import GetV2Events200Response from '../model/GetV2Events200Response';
import PostV2EventsComplete200Response from '../model/PostV2EventsComplete200Response';
import PostV2EventsCompleteRequest from '../model/PostV2EventsCompleteRequest';
import PostV2ResourcesCreatorUpdate200Response from '../model/PostV2ResourcesCreatorUpdate200Response';
import PostV2ResourcesCreatorUpdateRequest from '../model/PostV2ResourcesCreatorUpdateRequest';

/**
* Default service.
* @module api/DefaultApi
* @version v2
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2Analytics operation.
     * @callback module:api/DefaultApi~getV2AnalyticsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2Analytics200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of analytics definitions
     * @param {module:api/DefaultApi~getV2AnalyticsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2Analytics200Response}
     */
    getV2Analytics(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2Analytics200Response;
      return this.apiClient.callApi(
        '/v2/analytics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2AnalyticsGraph operation.
     * @callback module:api/DefaultApi~getV2AnalyticsGraphCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2AnalyticsGraph200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch analytics graph data
     * @param {Object} opts Optional parameters
     * @param {Array} [analytics] 
     * @param {String} [period] 
     * @param {String} [grouping] 
     * @param {String} [filters] 
     * @param {String} [startDate] Only respected when 'period' = 'custom_range'.
     * @param {String} [endDate] Only respected when 'period' = 'custom_range'.
     * @param {module:api/DefaultApi~getV2AnalyticsGraphCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2AnalyticsGraph200Response}
     */
    getV2AnalyticsGraph(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'analytics': opts['analytics'],
        'period': opts['period'],
        'grouping': opts['grouping'],
        'filters': opts['filters'],
        'start_date': opts['startDate'],
        'end_date': opts['endDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2AnalyticsGraph200Response;
      return this.apiClient.callApi(
        '/v2/analytics/graph', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2Events operation.
     * @callback module:api/DefaultApi~getV2EventsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2Events200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of pending events
     * @param {module:api/DefaultApi~getV2EventsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2Events200Response}
     */
    getV2Events(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2Events200Response;
      return this.apiClient.callApi(
        '/v2/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2EventsComplete operation.
     * @callback module:api/DefaultApi~postV2EventsCompleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2EventsComplete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mark events as complete
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2EventsCompleteRequest} [postV2EventsCompleteRequest] 
     * @param {module:api/DefaultApi~postV2EventsCompleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2EventsComplete200Response}
     */
    postV2EventsComplete(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2EventsCompleteRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2EventsComplete200Response;
      return this.apiClient.callApi(
        '/v2/events/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesCreatorUpdate operation.
     * @callback module:api/DefaultApi~postV2ResourcesCreatorUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesCreatorUpdate200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Post a resource update
     * Creates a new version for the resource and optionally posts a public update message. The uploaded file must be encoded using base64 as part of the JSON request body shown below.    The request body (including the base64 encoded file data) cannot exceed 100MB. This roughly equates to a 67MB upload limit for the raw file when taking into account base64 encoding losses.
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesCreatorUpdateRequest} [postV2ResourcesCreatorUpdateRequest] 
     * @param {module:api/DefaultApi~postV2ResourcesCreatorUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesCreatorUpdate200Response}
     */
    postV2ResourcesCreatorUpdate(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesCreatorUpdateRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesCreatorUpdate200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/update', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
