/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2ResourcesCreatorBatch200Response from '../model/GetV2ResourcesCreatorBatch200Response';
import PostV2ResourcesCreatorBatch200Response from '../model/PostV2ResourcesCreatorBatch200Response';
import PostV2ResourcesCreatorBatchRequest from '../model/PostV2ResourcesCreatorBatchRequest';

/**
* Default service.
* @module api/DefaultApi
* @version v2
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2ResourcesCreatorBatch operation.
     * @callback module:api/DefaultApi~getV2ResourcesCreatorBatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesCreatorBatch200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of your batches edits
     * @param {Object} opts Optional parameters
     * @param {Array} [batchIds] A comma-separated list of batch IDs to filter on. No filter is applied if empty.
     * @param {module:api/DefaultApi~getV2ResourcesCreatorBatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesCreatorBatch200Response}
     */
    getV2ResourcesCreatorBatch(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'batch_ids': opts['batchIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesCreatorBatch200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/batch', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesCreatorBatch operation.
     * @callback module:api/DefaultApi~postV2ResourcesCreatorBatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesCreatorBatch200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Submit a new batch edit
     * Batch edits will be processed in the background meaning a successful call to this endpoint does not guarantee that the edits have been completed. You will instead receive an identifier to a batch edit which you can then use to fetch the status of via the below endpoint. This is not an atomic operation meaning some resources may be edited successfully and others may not be due to an error. You may only batch edit resources you own currently.
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesCreatorBatchRequest} [postV2ResourcesCreatorBatchRequest] 
     * @param {module:api/DefaultApi~postV2ResourcesCreatorBatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesCreatorBatch200Response}
     */
    postV2ResourcesCreatorBatch(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesCreatorBatchRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesCreatorBatch200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
