/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2MembersSelf200Response from '../model/GetV2MembersSelf200Response';

/**
* Default service.
* @module api/DefaultApi
* @version v2
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2MembersSelf operation.
     * @callback module:api/DefaultApi~getV2MembersSelfCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2MembersSelf200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch self member information
     * See: https://builtbybit.com/help/developers/global-apis/members/
     * @param {module:api/DefaultApi~getV2MembersSelfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2MembersSelf200Response}
     */
    getV2MembersSelf(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2', 'token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2MembersSelf200Response;
      return this.apiClient.callApi(
        '/v2/members/self', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
