/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2Events200Response from '../model/GetV2Events200Response';
import PostV2EventsComplete200Response from '../model/PostV2EventsComplete200Response';
import PostV2EventsCompleteRequest from '../model/PostV2EventsCompleteRequest';

/**
* Events service.
* @module api/EventsApi
* @version v2
*/
export default class EventsApi {

    /**
    * Constructs a new EventsApi. 
    * @alias module:api/EventsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2Events operation.
     * @callback module:api/EventsApi~getV2EventsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2Events200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of pending events
     * @param {module:api/EventsApi~getV2EventsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2Events200Response}
     */
    getV2Events(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2Events200Response;
      return this.apiClient.callApi(
        '/v2/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2EventsComplete operation.
     * @callback module:api/EventsApi~postV2EventsCompleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2EventsComplete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mark events as complete
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2EventsCompleteRequest} [postV2EventsCompleteRequest] 
     * @param {module:api/EventsApi~postV2EventsCompleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2EventsComplete200Response}
     */
    postV2EventsComplete(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2EventsCompleteRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2EventsComplete200Response;
      return this.apiClient.callApi(
        '/v2/events/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
