/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2Analytics200Response from '../model/GetV2Analytics200Response';
import GetV2AnalyticsGraph200Response from '../model/GetV2AnalyticsGraph200Response';
import GetV2AnalyticsSingle200Response from '../model/GetV2AnalyticsSingle200Response';
import GetV2Events200Response from '../model/GetV2Events200Response';
import PostV2EventsComplete200Response from '../model/PostV2EventsComplete200Response';
import PostV2EventsCompleteRequest from '../model/PostV2EventsCompleteRequest';

/**
* Global service.
* @module api/GlobalApi
* @version v2
*/
export default class GlobalApi {

    /**
    * Constructs a new GlobalApi. 
    * @alias module:api/GlobalApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2Analytics operation.
     * @callback module:api/GlobalApi~getV2AnalyticsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2Analytics200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of analytics definitions
     * @param {module:api/GlobalApi~getV2AnalyticsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2Analytics200Response}
     */
    getV2Analytics(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2Analytics200Response;
      return this.apiClient.callApi(
        '/v2/analytics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2AnalyticsGraph operation.
     * @callback module:api/GlobalApi~getV2AnalyticsGraphCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2AnalyticsGraph200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch analytics graph data
     * @param {Object} opts Optional parameters
     * @param {Array} [analytics] A list of analytic IDs to fetch data for.
     * @param {String} [period] The time period to fetch data over.
     * @param {Array} [filters] A set of filters which may be used for the analytics.
     * @param {String} [startDate] Only respected when 'period' = 'custom_range', in the format 'YYYY-MM-DD'.
     * @param {String} [endDate] Only respected when 'period' = 'custom_range', in the format 'YYYY-MM-DD'.
     * @param {module:api/GlobalApi~getV2AnalyticsGraphCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2AnalyticsGraph200Response}
     */
    getV2AnalyticsGraph(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'analytics': opts['analytics'],
        'period': opts['period'],
        'filters': opts['filters'],
        'start_date': opts['startDate'],
        'end_date': opts['endDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2AnalyticsGraph200Response;
      return this.apiClient.callApi(
        '/v2/analytics/graph', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2AnalyticsSingle operation.
     * @callback module:api/GlobalApi~getV2AnalyticsSingleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2AnalyticsSingle200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a single analytics value
     * @param {Object} opts Optional parameters
     * @param {Array} [analytics] A list of analytic IDs to fetch data for.
     * @param {String} [period] The time period to fetch data over.
     * @param {Array} [filters] A set of filters which may be used for the analytics.
     * @param {String} [startDate] Only respected when 'period' = 'custom_range', in the format 'YYYY-MM-DD'.
     * @param {String} [endDate] Only respected when 'period' = 'custom_range', in the format 'YYYY-MM-DD'.
     * @param {module:api/GlobalApi~getV2AnalyticsSingleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2AnalyticsSingle200Response}
     */
    getV2AnalyticsSingle(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'analytics': opts['analytics'],
        'period': opts['period'],
        'filters': opts['filters'],
        'start_date': opts['startDate'],
        'end_date': opts['endDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2AnalyticsSingle200Response;
      return this.apiClient.callApi(
        '/v2/analytics/single', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2Events operation.
     * @callback module:api/GlobalApi~getV2EventsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2Events200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of pending events
     * @param {module:api/GlobalApi~getV2EventsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2Events200Response}
     */
    getV2Events(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2Events200Response;
      return this.apiClient.callApi(
        '/v2/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2EventsComplete operation.
     * @callback module:api/GlobalApi~postV2EventsCompleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2EventsComplete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mark events as complete
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2EventsCompleteRequest} [postV2EventsCompleteRequest] 
     * @param {module:api/GlobalApi~postV2EventsCompleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2EventsComplete200Response}
     */
    postV2EventsComplete(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2EventsCompleteRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2EventsComplete200Response;
      return this.apiClient.callApi(
        '/v2/events/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
