/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetOauth2Token200Response from '../model/GetOauth2Token200Response';
import GetOauth2TokenRevoke200Response from '../model/GetOauth2TokenRevoke200Response';

/**
* Oauth2 service.
* @module api/Oauth2Api
* @version v2
*/
export default class Oauth2Api {

    /**
    * Constructs a new Oauth2Api. 
    * @alias module:api/Oauth2Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getOauth2Token operation.
     * @callback module:api/Oauth2Api~getOauth2TokenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetOauth2Token200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Request an access token using an existing grant
     * Supported grant types: authorization_code, refresh_token
     * @param {String} authorization OAuth2 client credentials in the Basic authorization format.
     * @param {String} grantType 
     * @param {Object} opts Optional parameters
     * @param {String} [code] Required if grant_type = `authorization_code`.
     * @param {String} [refreshToken] Required if grant_type = `refresh_token`.
     * @param {module:api/Oauth2Api~getOauth2TokenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetOauth2Token200Response}
     */
    getOauth2Token(authorization, grantType, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getOauth2Token");
      }
      // verify the required parameter 'grantType' is set
      if (grantType === undefined || grantType === null) {
        throw new Error("Missing the required parameter 'grantType' when calling getOauth2Token");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Authorization': authorization
      };
      let formParams = {
        'grant_type': grantType,
        'code': opts['code'],
        'refresh_token': opts['refreshToken']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = GetOauth2Token200Response;
      return this.apiClient.callApi(
        '/oauth2/token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOauth2TokenRevoke operation.
     * @callback module:api/Oauth2Api~getOauth2TokenRevokeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetOauth2TokenRevoke200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke an existing access or refresh token
     * @param {String} authorization OAuth2 client credentials in the Basic authorization format.
     * @param {String} token 
     * @param {Object} opts Optional parameters
     * @param {String} [tokenHint] 
     * @param {module:api/Oauth2Api~getOauth2TokenRevokeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetOauth2TokenRevoke200Response}
     */
    getOauth2TokenRevoke(authorization, token, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getOauth2TokenRevoke");
      }
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling getOauth2TokenRevoke");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Authorization': authorization
      };
      let formParams = {
        'token': token,
        'token_hint': opts['tokenHint']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = GetOauth2TokenRevoke200Response;
      return this.apiClient.callApi(
        '/oauth2/token/revoke', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
