/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetResourcesDiscoverCategories200Response from '../model/GetResourcesDiscoverCategories200Response';
import GetResourcesDiscoverResources200Response from '../model/GetResourcesDiscoverResources200Response';
import GetResourcesDiscoverResources4XXResponse from '../model/GetResourcesDiscoverResources4XXResponse';
import GetV2ResourcesDiscoverDownloadDirectInitiate200Response from '../model/GetV2ResourcesDiscoverDownloadDirectInitiate200Response';
import GetV2ResourcesDiscoverDownloadDirectPoll200Response from '../model/GetV2ResourcesDiscoverDownloadDirectPoll200Response';
import GetV2ResourcesDiscoverLicenses200Response from '../model/GetV2ResourcesDiscoverLicenses200Response';

/**
* ResourcesDiscover service.
* @module api/ResourcesDiscoverApi
* @version v2
*/
export default class ResourcesDiscoverApi {

    /**
    * Constructs a new ResourcesDiscoverApi. 
    * @alias module:api/ResourcesDiscoverApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getResourcesDiscoverCategories operation.
     * @callback module:api/ResourcesDiscoverApi~getResourcesDiscoverCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetResourcesDiscoverCategories200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of categories
     * Supported 'with' hints:  - Children: includes all subcategories and their children
     * @param {Object} opts Optional parameters
     * @param {String} [categoryId] A category ID to filter on.
     * @param {module:model/String} [_with] A comma-separated list of submodels to include.
     * @param {module:api/ResourcesDiscoverApi~getResourcesDiscoverCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetResourcesDiscoverCategories200Response}
     */
    getResourcesDiscoverCategories(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'category_id': opts['categoryId'],
        'with': opts['_with']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetResourcesDiscoverCategories200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getResourcesDiscoverResources operation.
     * @callback module:api/ResourcesDiscoverApi~getResourcesDiscoverResourcesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetResourcesDiscoverResources200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of resources
     * Supported 'with' hints:  - `filters`: include dynamic filter information in the response.  - See 'Resource' model for additional 'with' hints.
     * @param {Object} opts Optional parameters
     * @param {String} [categoryId] A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included.
     * @param {String} [_with] A comma-separated list of additional data to include. See endpoint documentation for more information.
     * @param {Object.<String, Object>} [filters] A list of dynamic filters to apply.
     * @param {String} [resourceIds] A comma-separated list of resource IDs to filter on.
     * @param {Number} [page = 1)] The page number to return.
     * @param {Number} [perPage = 25)] The number of resources to return per page.
     * @param {Boolean} [noDependencies] Whether or not to exclude resources with dependencies listed.
     * @param {String} [excludedResourceIds] A comma-separated list of resource IDs to exclude. No filter will be applied if empty.
     * @param {String} [excludedCreatorIds] A comma-separated list of creator IDs to exclude. No filter will be applied if empty.
     * @param {module:api/ResourcesDiscoverApi~getResourcesDiscoverResourcesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetResourcesDiscoverResources200Response}
     */
    getResourcesDiscoverResources(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'category_id': opts['categoryId'],
        'with': opts['_with'],
        'filters': opts['filters'],
        'resource_ids': opts['resourceIds'],
        'page': opts['page'],
        'per_page': opts['perPage'],
        'no_dependencies': opts['noDependencies'],
        'excluded_resource_ids': opts['excludedResourceIds'],
        'excluded_creator_ids': opts['excludedCreatorIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetResourcesDiscoverResources200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/resources', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesDiscoverDownloadDirectInitiate operation.
     * @callback module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverDownloadDirectInitiateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesDiscoverDownloadDirectInitiate200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate a direct download request
     * See: https://builtbybit.com/help/developers/discovery-api/downloading-and-one-click/
     * @param {String} contentType Either 'resource' or 'resource_version'
     * @param {Number} contentId 
     * @param {module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverDownloadDirectInitiateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesDiscoverDownloadDirectInitiate200Response}
     */
    getV2ResourcesDiscoverDownloadDirectInitiate(contentType, contentId, callback) {
      let postBody = null;
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling getV2ResourcesDiscoverDownloadDirectInitiate");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling getV2ResourcesDiscoverDownloadDirectInitiate");
      }

      let pathParams = {
      };
      let queryParams = {
        'content_type': contentType,
        'content_id': contentId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesDiscoverDownloadDirectInitiate200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/download/direct/initiate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesDiscoverDownloadDirectPoll operation.
     * @callback module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverDownloadDirectPollCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesDiscoverDownloadDirectPoll200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch the status of a direct download request
     * See: https://builtbybit.com/help/developers/discovery-api/downloading-and-one-click/
     * @param {Object} opts Optional parameters
     * @param {String} [token] The download request token returned from an initiate request.
     * @param {module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverDownloadDirectPollCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesDiscoverDownloadDirectPoll200Response}
     */
    getV2ResourcesDiscoverDownloadDirectPoll(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'token': opts['token']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesDiscoverDownloadDirectPoll200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/download/direct/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesDiscoverLicenses operation.
     * @callback module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverLicensesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesDiscoverLicenses200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of the user's licenses
     * Supported 'with' hints:  - Resource: the resource the license is for if content_type = `resource`
     * @param {Object} opts Optional parameters
     * @param {Number} [page] The page number/offset to return items for.
     * @param {Number} [perPage = 25)] The number of items per page to return.
     * @param {String} [_with] A comma-separated list of supported 'with hints'. See model & endpoint-level docs for more info.
     * @param {module:api/ResourcesDiscoverApi~getV2ResourcesDiscoverLicensesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesDiscoverLicenses200Response}
     */
    getV2ResourcesDiscoverLicenses(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'with': opts['_with']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesDiscoverLicenses200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/licenses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
