/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2ResourcesCreatorCoupons200Response from '../model/GetV2ResourcesCreatorCoupons200Response';
import GetV2ResourcesCreatorCouponsEntries200Response from '../model/GetV2ResourcesCreatorCouponsEntries200Response';
import PostV2ResourcesCreatorCoupons200Response from '../model/PostV2ResourcesCreatorCoupons200Response';
import PostV2ResourcesCreatorCouponsRequest from '../model/PostV2ResourcesCreatorCouponsRequest';

/**
* ResourcesCreatorCoupons service.
* @module api/ResourcesCreatorCouponsApi
* @version v2
*/
export default class ResourcesCreatorCouponsApi {

    /**
    * Constructs a new ResourcesCreatorCouponsApi. 
    * @alias module:api/ResourcesCreatorCouponsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2ResourcesCreatorCoupons operation.
     * @callback module:api/ResourcesCreatorCouponsApi~getV2ResourcesCreatorCouponsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesCreatorCoupons200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of your coupons
     * @param {Object} opts Optional parameters
     * @param {Array} [couponIds] A comma-separated list of coupon IDs to filter on. No filter is applied if empty.
     * @param {module:api/ResourcesCreatorCouponsApi~getV2ResourcesCreatorCouponsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesCreatorCoupons200Response}
     */
    getV2ResourcesCreatorCoupons(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'coupon_ids': opts['couponIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesCreatorCoupons200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/coupons', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesCreatorCouponsEntries operation.
     * @callback module:api/ResourcesCreatorCouponsApi~getV2ResourcesCreatorCouponsEntriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesCreatorCouponsEntries200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of your coupon entries
     * @param {Object} opts Optional parameters
     * @param {Array} [couponIds] A comma-separated list of coupon IDs to filter on. No filter is applied if empty.
     * @param {module:api/ResourcesCreatorCouponsApi~getV2ResourcesCreatorCouponsEntriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesCreatorCouponsEntries200Response}
     */
    getV2ResourcesCreatorCouponsEntries(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'coupon_ids': opts['couponIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesCreatorCouponsEntries200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/coupons/entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesCreatorCoupons operation.
     * @callback module:api/ResourcesCreatorCouponsApi~postV2ResourcesCreatorCouponsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesCreatorCoupons200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new coupon
     * This endpoint is currently limited to percent-based coupons with a maximum discount of 50%.
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesCreatorCouponsRequest} [postV2ResourcesCreatorCouponsRequest] 
     * @param {module:api/ResourcesCreatorCouponsApi~postV2ResourcesCreatorCouponsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesCreatorCoupons200Response}
     */
    postV2ResourcesCreatorCoupons(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesCreatorCouponsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesCreatorCoupons200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/coupons', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
