/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PostV2ResourcesCreatorUpdate200Response from '../model/PostV2ResourcesCreatorUpdate200Response';
import PostV2ResourcesCreatorUpdateRequest from '../model/PostV2ResourcesCreatorUpdateRequest';

/**
* ResourcesCreator service.
* @module api/ResourcesCreatorApi
* @version v2
*/
export default class ResourcesCreatorApi {

    /**
    * Constructs a new ResourcesCreatorApi. 
    * @alias module:api/ResourcesCreatorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the postV2ResourcesCreatorUpdate operation.
     * @callback module:api/ResourcesCreatorApi~postV2ResourcesCreatorUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesCreatorUpdate200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Post a resource update
     * Creates a new version for the resource and optionally posts a public update message. The uploaded file must be encoded using base64 as part of the JSON request body shown below.    The request body (including the base64 encoded file data) cannot exceed 100MB. This roughly equates to a 67MB upload limit for the raw file when taking into account base64 encoding losses.
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesCreatorUpdateRequest} [postV2ResourcesCreatorUpdateRequest] 
     * @param {module:api/ResourcesCreatorApi~postV2ResourcesCreatorUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesCreatorUpdate200Response}
     */
    postV2ResourcesCreatorUpdate(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesCreatorUpdateRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesCreatorUpdate200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/update', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
