/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2ResourcesCreatorSaleEvents200Response from '../model/GetV2ResourcesCreatorSaleEvents200Response';
import GetV2ResourcesCreatorSaleEventsEntries200Response from '../model/GetV2ResourcesCreatorSaleEventsEntries200Response';

/**
* ResourcesCreatorSaleEvents service.
* @module api/ResourcesCreatorSaleEventsApi
* @version v2
*/
export default class ResourcesCreatorSaleEventsApi {

    /**
    * Constructs a new ResourcesCreatorSaleEventsApi. 
    * @alias module:api/ResourcesCreatorSaleEventsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2ResourcesCreatorSaleEvents operation.
     * @callback module:api/ResourcesCreatorSaleEventsApi~getV2ResourcesCreatorSaleEventsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesCreatorSaleEvents200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of your sale events
     * @param {Object} opts Optional parameters
     * @param {Array} [saleEventIds] A comma-separated list of sale event IDs to filter on. No filter is applied if empty.
     * @param {module:api/ResourcesCreatorSaleEventsApi~getV2ResourcesCreatorSaleEventsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesCreatorSaleEvents200Response}
     */
    getV2ResourcesCreatorSaleEvents(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'sale_event_ids': opts['saleEventIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesCreatorSaleEvents200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/sale-events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesCreatorSaleEventsEntries operation.
     * @callback module:api/ResourcesCreatorSaleEventsApi~getV2ResourcesCreatorSaleEventsEntriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesCreatorSaleEventsEntries200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch a list of your sale event entries
     * @param {Object} opts Optional parameters
     * @param {Array} [saleEventIds] A comma-separated list of sale event IDs to filter on. No filter is applied if empty.
     * @param {module:api/ResourcesCreatorSaleEventsApi~getV2ResourcesCreatorSaleEventsEntriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesCreatorSaleEventsEntries200Response}
     */
    getV2ResourcesCreatorSaleEventsEntries(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'sale_event_ids': opts['saleEventIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesCreatorSaleEventsEntries200Response;
      return this.apiClient.callApi(
        '/v2/resources/creator/sale-events/entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
