/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2ResourcesDiscoverCartView200Response from '../model/GetV2ResourcesDiscoverCartView200Response';
import PostV2ResourcesDiscoverCartAdd2XXResponse from '../model/PostV2ResourcesDiscoverCartAdd2XXResponse';
import PostV2ResourcesDiscoverCartAddRequest from '../model/PostV2ResourcesDiscoverCartAddRequest';
import PostV2ResourcesDiscoverCartCheckout200Response from '../model/PostV2ResourcesDiscoverCartCheckout200Response';
import PostV2ResourcesDiscoverCartCouponAdd200Response from '../model/PostV2ResourcesDiscoverCartCouponAdd200Response';
import PostV2ResourcesDiscoverCartCouponAddRequest from '../model/PostV2ResourcesDiscoverCartCouponAddRequest';
import PostV2ResourcesDiscoverCartCouponRemove200Response from '../model/PostV2ResourcesDiscoverCartCouponRemove200Response';
import PostV2ResourcesDiscoverCartCouponRemoveRequest from '../model/PostV2ResourcesDiscoverCartCouponRemoveRequest';
import PostV2ResourcesDiscoverCartRemove200Response from '../model/PostV2ResourcesDiscoverCartRemove200Response';
import PostV2ResourcesDiscoverCartRemoveRequest from '../model/PostV2ResourcesDiscoverCartRemoveRequest';

/**
* ResourcesDiscoverCart service.
* @module api/ResourcesDiscoverCartApi
* @version v2
*/
export default class ResourcesDiscoverCartApi {

    /**
    * Constructs a new ResourcesDiscoverCartApi. 
    * @alias module:api/ResourcesDiscoverCartApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2ResourcesDiscoverCartView operation.
     * @callback module:api/ResourcesDiscoverCartApi~getV2ResourcesDiscoverCartViewCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesDiscoverCartView200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View the user's cart items
     * 
     * @param {module:api/ResourcesDiscoverCartApi~getV2ResourcesDiscoverCartViewCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesDiscoverCartView200Response}
     */
    getV2ResourcesDiscoverCartView(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesDiscoverCartView200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/view', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesDiscoverCartAdd operation.
     * @callback module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartAddCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesDiscoverCartAdd2XXResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add items to a user's cart
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesDiscoverCartAddRequest} [postV2ResourcesDiscoverCartAddRequest] A list of content to add to the user's cart. The outer list is keyed by the content type and the inner list are the content IDs.    For instance, if adding a resource with the ID 555, the body becomes:  ```json  {\"add\": {\"resource\": [555]}}  ```
     * @param {module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartAddCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesDiscoverCartAdd2XXResponse}
     */
    postV2ResourcesDiscoverCartAdd(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesDiscoverCartAddRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesDiscoverCartAdd2XXResponse;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesDiscoverCartCheckout operation.
     * @callback module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCheckoutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesDiscoverCartCheckout200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate a checkout of a user's cart
     * @param {Object} opts Optional parameters
     * @param {Object.<String, Object>} [body] 
     * @param {module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCheckoutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesDiscoverCartCheckout200Response}
     */
    postV2ResourcesDiscoverCartCheckout(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesDiscoverCartCheckout200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/checkout', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesDiscoverCartCouponAdd operation.
     * @callback module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCouponAddCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesDiscoverCartCouponAdd200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a coupon to the user's cart
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesDiscoverCartCouponAddRequest} [postV2ResourcesDiscoverCartCouponAddRequest] 
     * @param {module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCouponAddCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesDiscoverCartCouponAdd200Response}
     */
    postV2ResourcesDiscoverCartCouponAdd(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesDiscoverCartCouponAddRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesDiscoverCartCouponAdd200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/coupon/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesDiscoverCartCouponRemove operation.
     * @callback module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCouponRemoveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesDiscoverCartCouponRemove200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove a coupon from the user's cart
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesDiscoverCartCouponRemoveRequest} [postV2ResourcesDiscoverCartCouponRemoveRequest] 
     * @param {module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartCouponRemoveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesDiscoverCartCouponRemove200Response}
     */
    postV2ResourcesDiscoverCartCouponRemove(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesDiscoverCartCouponRemoveRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesDiscoverCartCouponRemove200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/coupon/remove', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV2ResourcesDiscoverCartRemove operation.
     * @callback module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartRemoveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostV2ResourcesDiscoverCartRemove200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove an item from the user's cart
     * @param {Object} opts Optional parameters
     * @param {module:model/PostV2ResourcesDiscoverCartRemoveRequest} [postV2ResourcesDiscoverCartRemoveRequest] 
     * @param {module:api/ResourcesDiscoverCartApi~postV2ResourcesDiscoverCartRemoveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostV2ResourcesDiscoverCartRemove200Response}
     */
    postV2ResourcesDiscoverCartRemove(opts, callback) {
      opts = opts || {};
      let postBody = opts['postV2ResourcesDiscoverCartRemoveRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV2ResourcesDiscoverCartRemove200Response;
      return this.apiClient.callApi(
        '/v2/resources/discover/cart/remove', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
