/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetV2ResourcesEmbedDownloadInitiate200Response from '../model/GetV2ResourcesEmbedDownloadInitiate200Response';
import GetV2ResourcesEmbedDownloadStatus200Response from '../model/GetV2ResourcesEmbedDownloadStatus200Response';
import GetV2ResourcesEmbedLatest200Response from '../model/GetV2ResourcesEmbedLatest200Response';

/**
* ResourcesEmbed service.
* @module api/ResourcesEmbedApi
* @version v2
*/
export default class ResourcesEmbedApi {

    /**
    * Constructs a new ResourcesEmbedApi. 
    * @alias module:api/ResourcesEmbedApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV2ResourcesEmbedDownloadInitiate operation.
     * @callback module:api/ResourcesEmbedApi~getV2ResourcesEmbedDownloadInitiateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesEmbedDownloadInitiate200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate a download request
     * See: https://builtbybit.com/help/developers/resource-apis/embed/
     * @param {String} contentType Either 'resource', 'resource_version', 'api_asset'
     * @param {Number} contentId 
     * @param {String} nonce 32 character hash provided by an anti-piracy placeholder of the NONCE type. Must be from a resource download (cannot be an addon download’s nonce, etc).
     * @param {module:api/ResourcesEmbedApi~getV2ResourcesEmbedDownloadInitiateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesEmbedDownloadInitiate200Response}
     */
    getV2ResourcesEmbedDownloadInitiate(contentType, contentId, nonce, callback) {
      let postBody = null;
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling getV2ResourcesEmbedDownloadInitiate");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling getV2ResourcesEmbedDownloadInitiate");
      }
      // verify the required parameter 'nonce' is set
      if (nonce === undefined || nonce === null) {
        throw new Error("Missing the required parameter 'nonce' when calling getV2ResourcesEmbedDownloadInitiate");
      }

      let pathParams = {
      };
      let queryParams = {
        'content_type': contentType,
        'content_id': contentId,
        'nonce': nonce
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesEmbedDownloadInitiate200Response;
      return this.apiClient.callApi(
        '/v2/resources/embed/download/initiate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesEmbedDownloadStatus operation.
     * @callback module:api/ResourcesEmbedApi~getV2ResourcesEmbedDownloadStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesEmbedDownloadStatus200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch the status of a download request
     * See: https://builtbybit.com/help/developers/resource-apis/embed/
     * @param {Object} opts Optional parameters
     * @param {String} [token] The download request token returned from an initiate request.
     * @param {module:api/ResourcesEmbedApi~getV2ResourcesEmbedDownloadStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesEmbedDownloadStatus200Response}
     */
    getV2ResourcesEmbedDownloadStatus(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'token': opts['token']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesEmbedDownloadStatus200Response;
      return this.apiClient.callApi(
        '/v2/resources/embed/download/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV2ResourcesEmbedLatest operation.
     * @callback module:api/ResourcesEmbedApi~getV2ResourcesEmbedLatestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetV2ResourcesEmbedLatest200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetches the latest versions & license information
     * See: https://builtbybit.com/help/developers/resource-apis/embed/
     * @param {Object} opts Optional parameters
     * @param {String} [nonce] 32 character hash provided by an anti-piracy placeholder of the NONCE type. Must be from a resource download (cannot be an addon download’s nonce, etc).
     * @param {module:api/ResourcesEmbedApi~getV2ResourcesEmbedLatestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetV2ResourcesEmbedLatest200Response}
     */
    getV2ResourcesEmbedLatest(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'nonce': opts['nonce']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV2ResourcesEmbedLatest200Response;
      return this.apiClient.callApi(
        '/v2/resources/embed/latest', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
