/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.CartSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CartSummary', function() {
    it('should create an instance of CartSummary', function() {
      // uncomment below and update the code to test CartSummary
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be.a(BuiltByBitApi.CartSummary);
    });

    it('should have the property listPrice (base name: "list_price")', function() {
      // uncomment below and update the code to test the property listPrice
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

    it('should have the property listPriceFormatted (base name: "list_price_formatted")', function() {
      // uncomment below and update the code to test the property listPriceFormatted
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

    it('should have the property finalPrice (base name: "final_price")', function() {
      // uncomment below and update the code to test the property finalPrice
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

    it('should have the property finalPriceFormatted (base name: "final_price_formatted")', function() {
      // uncomment below and update the code to test the property finalPriceFormatted
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

    it('should have the property notice (base name: "notice")', function() {
      // uncomment below and update the code to test the property notice
      //var instance = new BuiltByBitApi.CartSummary();
      //expect(instance).to.be();
    });

  });

}));
