/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.Event();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Event', function() {
    it('should create an instance of Event', function() {
      // uncomment below and update the code to test Event
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be.a(BuiltByBitApi.Event);
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property listenerId (base name: "listener_id")', function() {
      // uncomment below and update the code to test the property listenerId
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property triggerType (base name: "trigger_type")', function() {
      // uncomment below and update the code to test the property triggerType
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property triggerData (base name: "trigger_data")', function() {
      // uncomment below and update the code to test the property triggerData
      //var instance = new BuiltByBitApi.Event();
      //expect(instance).to.be();
    });

  });

}));
