/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV2ResourcesCreatorCouponsRequest', function() {
    it('should create an instance of PostV2ResourcesCreatorCouponsRequest', function() {
      // uncomment below and update the code to test PostV2ResourcesCreatorCouponsRequest
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be.a(BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property doExpiry (base name: "do_expiry")', function() {
      // uncomment below and update the code to test the property doExpiry
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiry_date")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property limitedUses (base name: "limited_uses")', function() {
      // uncomment below and update the code to test the property limitedUses
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxUses (base name: "max_uses")', function() {
      // uncomment below and update the code to test the property maxUses
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property limitedUserUses (base name: "limited_user_uses")', function() {
      // uncomment below and update the code to test the property limitedUserUses
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxPerUserUses (base name: "max_per_user_uses")', function() {
      // uncomment below and update the code to test the property maxPerUserUses
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property allContentTypes (base name: "all_content_types")', function() {
      // uncomment below and update the code to test the property allContentTypes
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property resources (base name: "resources")', function() {
      // uncomment below and update the code to test the property resources
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property addons (base name: "addons")', function() {
      // uncomment below and update the code to test the property addons
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

    it('should have the property bundles (base name: "bundles")', function() {
      // uncomment below and update the code to test the property bundles
      //var instance = new BuiltByBitApi.PostV2ResourcesCreatorCouponsRequest();
      //expect(instance).to.be();
    });

  });

}));
