/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.PostV2DeploymentsUpgradeRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV2DeploymentsUpgradeRequest', function() {
    it('should create an instance of PostV2DeploymentsUpgradeRequest', function() {
      // uncomment below and update the code to test PostV2DeploymentsUpgradeRequest
      //var instance = new BuiltByBitApi.PostV2DeploymentsUpgradeRequest();
      //expect(instance).to.be.a(BuiltByBitApi.PostV2DeploymentsUpgradeRequest);
    });

    it('should have the property preauthorize (base name: "preauthorize")', function() {
      // uncomment below and update the code to test the property preauthorize
      //var instance = new BuiltByBitApi.PostV2DeploymentsUpgradeRequest();
      //expect(instance).to.be();
    });

    it('should have the property scopes (base name: "scopes")', function() {
      // uncomment below and update the code to test the property scopes
      //var instance = new BuiltByBitApi.PostV2DeploymentsUpgradeRequest();
      //expect(instance).to.be();
    });

  });

}));
