/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.Resource();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Resource', function() {
    it('should create an instance of Resource', function() {
      // uncomment below and update the code to test Resource
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be.a(BuiltByBitApi.Resource);
    });

    it('should have the property resourceId (base name: "resource_id")', function() {
      // uncomment below and update the code to test the property resourceId
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property creatorId (base name: "creator_id")', function() {
      // uncomment below and update the code to test the property creatorId
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property publishedAt (base name: "published_at")', function() {
      // uncomment below and update the code to test the property publishedAt
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
      // uncomment below and update the code to test the property lastUpdatedAt
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property purchases (base name: "purchases")', function() {
      // uncomment below and update the code to test the property purchases
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property downloads (base name: "downloads")', function() {
      // uncomment below and update the code to test the property downloads
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property listPrice (base name: "list_price")', function() {
      // uncomment below and update the code to test the property listPrice
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property coverImageUrl (base name: "cover_image_url")', function() {
      // uncomment below and update the code to test the property coverImageUrl
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property finalPrice (base name: "final_price")', function() {
      // uncomment below and update the code to test the property finalPrice
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property finalPriceFormatted (base name: "final_price_formatted")', function() {
      // uncomment below and update the code to test the property finalPriceFormatted
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property listPriceFormatted (base name: "list_price_formatted")', function() {
      // uncomment below and update the code to test the property listPriceFormatted
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property carouselImageUrls (base name: "carousel_image_urls")', function() {
      // uncomment below and update the code to test the property carouselImageUrls
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property reviewCount (base name: "review_count")', function() {
      // uncomment below and update the code to test the property reviewCount
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property reviewAverage (base name: "review_average")', function() {
      // uncomment below and update the code to test the property reviewAverage
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property saleEventEntry (base name: "SaleEventEntry")', function() {
      // uncomment below and update the code to test the property saleEventEntry
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "Creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property latestVersion (base name: "LatestVersion")', function() {
      // uncomment below and update the code to test the property latestVersion
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property latestUpdate (base name: "LatestUpdate")', function() {
      // uncomment below and update the code to test the property latestUpdate
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property latestReviews (base name: "LatestReviews")', function() {
      // uncomment below and update the code to test the property latestReviews
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "Category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

    it('should have the property addons (base name: "Addons")', function() {
      // uncomment below and update the code to test the property addons
      //var instance = new BuiltByBitApi.Resource();
      //expect(instance).to.be();
    });

  });

}));
