/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.SaleEventEntry();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SaleEventEntry', function() {
    it('should create an instance of SaleEventEntry', function() {
      // uncomment below and update the code to test SaleEventEntry
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be.a(BuiltByBitApi.SaleEventEntry);
    });

    it('should have the property entryId (base name: "entry_id")', function() {
      // uncomment below and update the code to test the property entryId
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "content_type")', function() {
      // uncomment below and update the code to test the property contentType
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

    it('should have the property contentId (base name: "content_id")', function() {
      // uncomment below and update the code to test the property contentId
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

    it('should have the property saleEvent (base name: "SaleEvent")', function() {
      // uncomment below and update the code to test the property saleEvent
      //var instance = new BuiltByBitApi.SaleEventEntry();
      //expect(instance).to.be();
    });

  });

}));
