/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.ResourcesDiscoveryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResourcesDiscoveryApi', function() {
    describe('getResourcesDiscoverCategories', function() {
      it('should call getResourcesDiscoverCategories successfully', function(done) {
        //uncomment below and update the code to test getResourcesDiscoverCategories
        //instance.getResourcesDiscoverCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getResourcesDiscoverResources', function() {
      it('should call getResourcesDiscoverResources successfully', function(done) {
        //uncomment below and update the code to test getResourcesDiscoverResources
        //instance.getResourcesDiscoverResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV2ResourcesDiscoverCartView', function() {
      it('should call getV2ResourcesDiscoverCartView successfully', function(done) {
        //uncomment below and update the code to test getV2ResourcesDiscoverCartView
        //instance.getV2ResourcesDiscoverCartView(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV2ResourcesDiscoverLicenses', function() {
      it('should call getV2ResourcesDiscoverLicenses successfully', function(done) {
        //uncomment below and update the code to test getV2ResourcesDiscoverLicenses
        //instance.getV2ResourcesDiscoverLicenses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesDiscoverCartAdd', function() {
      it('should call postV2ResourcesDiscoverCartAdd successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesDiscoverCartAdd
        //instance.postV2ResourcesDiscoverCartAdd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesDiscoverCartCheckout', function() {
      it('should call postV2ResourcesDiscoverCartCheckout successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesDiscoverCartCheckout
        //instance.postV2ResourcesDiscoverCartCheckout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesDiscoverCartCouponAdd', function() {
      it('should call postV2ResourcesDiscoverCartCouponAdd successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesDiscoverCartCouponAdd
        //instance.postV2ResourcesDiscoverCartCouponAdd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesDiscoverCartCouponRemove', function() {
      it('should call postV2ResourcesDiscoverCartCouponRemove successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesDiscoverCartCouponRemove
        //instance.postV2ResourcesDiscoverCartCouponRemove(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesDiscoverCartRemove', function() {
      it('should call postV2ResourcesDiscoverCartRemove successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesDiscoverCartRemove
        //instance.postV2ResourcesDiscoverCartRemove(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
