/**
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuiltByBitApi);
  }
}(this, function(expect, BuiltByBitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuiltByBitApi.ResourcesCreatorCouponsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResourcesCreatorCouponsApi', function() {
    describe('getV2ResourcesCreatorCoupons', function() {
      it('should call getV2ResourcesCreatorCoupons successfully', function(done) {
        //uncomment below and update the code to test getV2ResourcesCreatorCoupons
        //instance.getV2ResourcesCreatorCoupons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV2ResourcesCreatorCouponsEntries', function() {
      it('should call getV2ResourcesCreatorCouponsEntries successfully', function(done) {
        //uncomment below and update the code to test getV2ResourcesCreatorCouponsEntries
        //instance.getV2ResourcesCreatorCouponsEntries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV2ResourcesCreatorCoupons', function() {
      it('should call postV2ResourcesCreatorCoupons successfully', function(done) {
        //uncomment below and update the code to test postV2ResourcesCreatorCoupons
        //instance.postV2ResourcesCreatorCoupons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
